const CACHE_NAME = 'rmmz-offline-cache-v2';

// 1. THE MASTER LIST
const PRECACHE_URLS = [
    './',
    './index.html',
    './package.json',
    './Test.json',
    
    './audio/bgm/Battle1.ogg',
    './audio/bgm/Battle2.ogg',
    './audio/bgm/Battle3.ogg',
    './audio/bgm/Battle4.ogg',
    './audio/bgm/Battle5.ogg',
    './audio/bgm/Battle6.ogg',
    './audio/bgm/Battle7.ogg',
    './audio/bgm/Battle8.ogg',
    './audio/bgm/Castle1.ogg',
    './audio/bgm/Castle2.ogg',
    './audio/bgm/Castle3.ogg',
    './audio/bgm/Dungeon1.ogg',
    './audio/bgm/Dungeon2.ogg',
    './audio/bgm/Dungeon3.ogg',
    './audio/bgm/Dungeon4.ogg',
    './audio/bgm/Dungeon5.ogg',
    './audio/bgm/Dungeon6.ogg',
    './audio/bgm/Dungeon7.ogg',
    './audio/bgm/Field1.ogg',
    './audio/bgm/Field2.ogg',
    './audio/bgm/Field3.ogg',
    './audio/bgm/Field4.ogg',
    './audio/bgm/Scene1.ogg',
    './audio/bgm/Scene2.ogg',
    './audio/bgm/Scene3.ogg',
    './audio/bgm/Scene4.ogg',
    './audio/bgm/Scene5.ogg',
    './audio/bgm/Scene6.ogg',
    './audio/bgm/Scene7.ogg',
    './audio/bgm/Scene8.ogg',
    './audio/bgm/Scene9.ogg',
    './audio/bgm/Ship1.ogg',
    './audio/bgm/Ship2.ogg',
    './audio/bgm/Ship3.ogg',
    './audio/bgm/Theme1.ogg',
    './audio/bgm/Theme2.ogg',
    './audio/bgm/Theme3.ogg',
    './audio/bgm/Theme4.ogg',
    './audio/bgm/Theme5.ogg',
    './audio/bgm/Theme6.ogg',
    './audio/bgm/Town1.ogg',
    './audio/bgm/Town2.ogg',
    './audio/bgm/Town3.ogg',
    './audio/bgm/Town4.ogg',
    './audio/bgm/Town5.ogg',
    './audio/bgm/Town6.ogg',
    './audio/bgm/Town7.ogg',
    './audio/bgm/Town8.ogg',

    './audio/bgs/City.ogg',
    './audio/bgs/Clock.ogg',
    './audio/bgs/Darkness.ogg',
    './audio/bgs/Drips.ogg',
    './audio/bgs/Fire1.ogg',
    './audio/bgs/Fire2.ogg',
    './audio/bgs/Fire3.ogg',
    './audio/bgs/Night.ogg',
    './audio/bgs/People1.ogg',
    './audio/bgs/People2.ogg',
    './audio/bgs/Quake1.ogg',
    './audio/bgs/Quake2.ogg',
    './audio/bgs/Rain1.ogg',
    './audio/bgs/Rain2.ogg',
    './audio/bgs/Rain3.ogg',
    './audio/bgs/Rain4.ogg',
    './audio/bgs/River.ogg',
    './audio/bgs/Sea.ogg',
    './audio/bgs/Storm1.ogg',
    './audio/bgs/Storm2.ogg',
    './audio/bgs/Waterfall1.ogg',
    './audio/bgs/Waterfall2.ogg',
    './audio/bgs/Wave1.ogg',
    './audio/bgs/Wave2.ogg',
    './audio/bgs/Wind1.ogg',
    './audio/bgs/Wind2.ogg',
    './audio/bgs/Wind3.ogg',
    './audio/bgs/Wind4.ogg',
    './audio/bgs/Wind5.ogg',

    './audio/me/Curse1.ogg',
    './audio/me/Curse2.ogg',
    './audio/me/Defeat1.ogg',
    './audio/me/Defeat2.ogg',
    './audio/me/Fanfare1.ogg',
    './audio/me/Fanfare2.ogg',
    './audio/me/Fanfare3.ogg',
    './audio/me/Gag.ogg',
    './audio/me/Gameover1.ogg',
    './audio/me/Gameover2.ogg',
    './audio/me/Horror.ogg',
    './audio/me/Inn1.ogg',
    './audio/me/Inn2.ogg',
    './audio/me/Item.ogg',
    './audio/me/Like.ogg',
    './audio/me/Musical1.ogg',
    './audio/me/Musical2.ogg',
    './audio/me/Musical3.ogg',
    './audio/me/Mystery.ogg',
    './audio/me/Organ.ogg',
    './audio/me/Refresh.ogg',
    './audio/me/Shock1.ogg',
    './audio/me/Shock2.ogg',
    './audio/me/Shock3.ogg',
    './audio/me/Victory1.ogg',
    './audio/me/Victory2.ogg',
    './audio/me/Victory3.ogg',

    './audio/se/Absorb1.ogg',
    './audio/se/Absorb2.ogg',
    './audio/se/Applause1.ogg',
    './audio/se/Applause2.ogg',
    './audio/se/Attack1.ogg',
    './audio/se/Attack2.ogg',
    './audio/se/Attack3.ogg',
    './audio/se/Autodoor.ogg',
    './audio/se/Barrier.ogg',
    './audio/se/Battle1.ogg',
    './audio/se/Battle2.ogg',
    './audio/se/Battle3.ogg',
    './audio/se/Battle4.ogg',
    './audio/se/Battle5.ogg',
    './audio/se/Battle6.ogg',
    './audio/se/Bell1.ogg',
    './audio/se/Bell2.ogg',
    './audio/se/Bell3.ogg',
    './audio/se/Bite.ogg',
    './audio/se/Blind.ogg',
    './audio/se/Blow1.ogg',
    './audio/se/Blow10.ogg',
    './audio/se/Blow2.ogg',
    './audio/se/Blow3.ogg',
    './audio/se/Blow4.ogg',
    './audio/se/Blow5.ogg',
    './audio/se/Blow6.ogg',
    './audio/se/Blow7.ogg',
    './audio/se/Blow8.ogg',
    './audio/se/Blow9.ogg',
    './audio/se/Book1.ogg',
    './audio/se/Book2.ogg',
    './audio/se/Bow1.ogg',
    './audio/se/Bow2.ogg',
    './audio/se/Bow3.ogg',
    './audio/se/Bow4.ogg',
    './audio/se/Bow5.ogg',
    './audio/se/Break.ogg',
    './audio/se/Breath.ogg',
    './audio/se/Buzzer1.ogg',
    './audio/se/Buzzer2.ogg',
    './audio/se/Buzzer3.ogg',
    './audio/se/Cancel1.ogg',
    './audio/se/Cancel2.ogg',
    './audio/se/Cancel3.ogg',
    './audio/se/Cat.ogg',
    './audio/se/Chain.ogg',
    './audio/se/Chest1.ogg',
    './audio/se/Chest2.ogg',
    './audio/se/Chicken.ogg',
    './audio/se/Chime1.ogg',
    './audio/se/Chime2.ogg',

    './audio/se/Close1.ogg',
    './audio/se/Close2.ogg',
    './audio/se/Close3.ogg',
    './audio/se/Coin.ogg',
    './audio/se/Collapse1.ogg',
    './audio/se/Collapse2.ogg',
    './audio/se/Collapse3.ogg',
    './audio/se/Collapse4.ogg',
    './audio/se/Computer.ogg',
    './audio/se/Confuse.ogg',
    './audio/se/Cow.ogg',
    './audio/se/Crash.ogg',
    './audio/se/Crossbow.ogg',
    './audio/se/Crow.ogg',
    './audio/se/Cry1.ogg',
    './audio/se/Cry2.ogg',
    './audio/se/Cursor1.ogg',
    './audio/se/Cursor2.ogg',
    './audio/se/Cursor3.ogg',
    './audio/se/Cursor4.ogg',
    './audio/se/Damage1.ogg',
    './audio/se/Damage2.ogg',
    './audio/se/Damage3.ogg',
    './audio/se/Damage4.ogg',
    './audio/se/Damage5.ogg',
    './audio/se/Darkness1.ogg',
    './audio/se/Darkness2.ogg',
    './audio/se/Darkness3.ogg',
    './audio/se/Darkness4.ogg',
    './audio/se/Darkness5.ogg',
    './audio/se/Darkness6.ogg',
    './audio/se/Darkness7.ogg',
    './audio/se/Darkness8.ogg',
    './audio/se/Decision1.ogg',
    './audio/se/Decision2.ogg',
    './audio/se/Decision3.ogg',
    './audio/se/Decision4.ogg',
    './audio/se/Decision5.ogg',
    './audio/se/Devil1.ogg',
    './audio/se/Devil2.ogg',
    './audio/se/Devil3.ogg',
    './audio/se/Disappointment.ogg',
    './audio/se/Dive.ogg',
    './audio/se/Dog.ogg',
    './audio/se/Door1.ogg',
    './audio/se/Door2.ogg',
    './audio/se/Door3.ogg',
    './audio/se/Door4.ogg',
    './audio/se/Door5.ogg',
    './audio/se/Door6.ogg',
    './audio/se/Door7.ogg',
    './audio/se/Door8.ogg',
    './audio/se/Down1.ogg',
    './audio/se/Down2.ogg',
    './audio/se/Down3.ogg',
    './audio/se/Down4.ogg',
    './audio/se/Down5.ogg',
    './audio/se/Down6.ogg',
    './audio/se/Down7.ogg',

    './audio/se/Earth1.ogg',
    './audio/se/Earth2.ogg',
    './audio/se/Earth3.ogg',
    './audio/se/Earth4.ogg',
    './audio/se/Earth5.ogg',
    './audio/se/Electrocardiogram.ogg',
    './audio/se/Equip1.ogg',
    './audio/se/Equip2.ogg',
    './audio/se/Equip3.ogg',
    './audio/se/Evasion1.ogg',
    './audio/se/Evasion2.ogg',
    './audio/se/Explosion1.ogg',
    './audio/se/Explosion2.ogg',
    './audio/se/Explosion3.ogg',
    './audio/se/Explosion4.ogg',
    './audio/se/Fall.ogg',
    './audio/se/Fire1.ogg',
    './audio/se/Fire2.ogg',
    './audio/se/Fire3.ogg',
    './audio/se/Fire4.ogg',
    './audio/se/Fire5.ogg',
    './audio/se/Fire6.ogg',
    './audio/se/Fire7.ogg',
    './audio/se/Fire8.ogg',
    './audio/se/Fire9.ogg',
    './audio/se/Flash1.ogg',
    './audio/se/Flash2.ogg',
    './audio/se/Flash3.ogg',
    './audio/se/Float1.ogg',
    './audio/se/Float2.ogg',
    './audio/se/Fog1.ogg',
    './audio/se/Fog2.ogg',
    './audio/se/Frog.ogg',
    './audio/se/Gate1.ogg',
    './audio/se/Gate2.ogg',
    './audio/se/Growl.ogg',
    './audio/se/Gun1.ogg',
    './audio/se/Gun2.ogg',
    './audio/se/Gun3.ogg',
    './audio/se/Hammer.ogg',
    './audio/se/Heal1.ogg',
    './audio/se/Heal2.ogg',
    './audio/se/Heal3.ogg',
    './audio/se/Heal4.ogg',
    './audio/se/Heal5.ogg',
    './audio/se/Heal6.ogg',
    './audio/se/Heal7.ogg',
    './audio/se/Horn.ogg',
    './audio/se/Horse.ogg',

    './audio/se/Ice1.ogg',
    './audio/se/Ice10.ogg',
    './audio/se/Ice11.ogg',
    './audio/se/Ice2.ogg',
    './audio/se/Ice3.ogg',
    './audio/se/Ice4.ogg',
    './audio/se/Ice5.ogg',
    './audio/se/Ice6.ogg',
    './audio/se/Ice7.ogg',
    './audio/se/Ice8.ogg',
    './audio/se/Ice9.ogg',
    './audio/se/Item1.ogg',
    './audio/se/Item2.ogg',
    './audio/se/Item3.ogg',
    './audio/se/Jump1.ogg',
    './audio/se/Jump2.ogg',
    './audio/se/Key.ogg',
    './audio/se/Knock.ogg',
    './audio/se/Laser1.ogg',
    './audio/se/Laser2.ogg',
    './audio/se/Laugh.ogg',
    './audio/se/Launch.ogg',
    './audio/se/Leakage.ogg',
    './audio/se/Liquid.ogg',
    './audio/se/Load1.ogg',
    './audio/se/Load2.ogg',
    './audio/se/Machine.ogg',
    './audio/se/Magic1.ogg',
    './audio/se/Magic10.ogg',
    './audio/se/Magic11.ogg',
    './audio/se/Magic12.ogg',
    './audio/se/Magic2.ogg',
    './audio/se/Magic3.ogg',
    './audio/se/Magic4.ogg',
    './audio/se/Magic5.ogg',
    './audio/se/Magic6.ogg',
    './audio/se/Magic7.ogg',
    './audio/se/Magic8.ogg',
    './audio/se/Magic9.ogg',
    './audio/se/Miss.ogg',
    './audio/se/Monster1.ogg',
    './audio/se/Monster10.ogg',
    './audio/se/Monster2.ogg',
    './audio/se/Monster3.ogg',
    './audio/se/Monster4.ogg',
    './audio/se/Monster5.ogg',
    './audio/se/Monster6.ogg',
    './audio/se/Monster7.ogg',
    './audio/se/Monster8.ogg',
    './audio/se/Monster9.ogg',

    './audio/se/Move1.ogg',
    './audio/se/Move10.ogg',
    './audio/se/Move2.ogg',
    './audio/se/Move3.ogg',
    './audio/se/Move4.ogg',
    './audio/se/Move5.ogg',
    './audio/se/Move6.ogg',
    './audio/se/Move7.ogg',
    './audio/se/Move8.ogg',
    './audio/se/Move9.ogg',
    './audio/se/Neon.ogg',
    './audio/se/Noise.ogg',
    './audio/se/Open1.ogg',
    './audio/se/Open2.ogg',
    './audio/se/Open3.ogg',
    './audio/se/Open4.ogg',
    './audio/se/Open5.ogg',
    './audio/se/Open6.ogg',
    './audio/se/Open7.ogg',
    './audio/se/Open8.ogg',
    './audio/se/Open9.ogg',
    './audio/se/Paralyze1.ogg',
    './audio/se/Paralyze2.ogg',
    './audio/se/Paralyze3.ogg',
    './audio/se/Parry.ogg',
    './audio/se/Particles1.ogg',
    './audio/se/Particles2.ogg',
    './audio/se/Particles3.ogg',
    './audio/se/Particles4.ogg',
    './audio/se/Phone.ogg',
    './audio/se/Poison.ogg',
    './audio/se/Pollen.ogg',
    './audio/se/Powerup.ogg',
    './audio/se/Push.ogg',
    './audio/se/Raise1.ogg',
    './audio/se/Raise2.ogg',
    './audio/se/Raise3.ogg',
    './audio/se/Recovery.ogg',
    './audio/se/Reflection.ogg',
    './audio/se/Resonance.ogg',
    './audio/se/Run.ogg',
    './audio/se/Saint1.ogg',
    './audio/se/Saint2.ogg',
    './audio/se/Saint3.ogg',
    './audio/se/Saint4.ogg',
    './audio/se/Saint5.ogg',
    './audio/se/Saint6.ogg',
    './audio/se/Saint7.ogg',
    './audio/se/Saint8.ogg',
    './audio/se/Saint9.ogg',
    './audio/se/Sand.ogg',
    './audio/se/Save1.ogg',
    './audio/se/Save2.ogg',
    './audio/se/Scream.ogg',
    './audio/se/Sheep.ogg',

    './audio/se/Shop1.ogg',
    './audio/se/Shop2.ogg',
    './audio/se/Shot1.ogg',
    './audio/se/Shot2.ogg',
    './audio/se/Shot3.ogg',
    './audio/se/Silence.ogg',
    './audio/se/Siren.ogg',
    './audio/se/Skill1.ogg',
    './audio/se/Skill2.ogg',
    './audio/se/Skill3.ogg',
    './audio/se/Slash1.ogg',
    './audio/se/Slash10.ogg',
    './audio/se/Slash2.ogg',
    './audio/se/Slash3.ogg',
    './audio/se/Slash4.ogg',
    './audio/se/Slash5.ogg',
    './audio/se/Slash6.ogg',
    './audio/se/Slash7.ogg',
    './audio/se/Slash8.ogg',
    './audio/se/Slash9.ogg',
    './audio/se/Sleep.ogg',
    './audio/se/Sound1.ogg',
    './audio/se/Sound2.ogg',
    './audio/se/Sound3.ogg',
    './audio/se/Splash.ogg',
    './audio/se/Stare.ogg',
    './audio/se/Starlight.ogg',
    './audio/se/Summon.ogg',
    './audio/se/Switch1.ogg',
    './audio/se/Switch2.ogg',
    './audio/se/Switch3.ogg',
    './audio/se/Sword1.ogg',
    './audio/se/Sword2.ogg',
    './audio/se/Sword3.ogg',
    './audio/se/Sword4.ogg',
    './audio/se/Sword5.ogg',
    './audio/se/Sword6.ogg',
    './audio/se/Sword7.ogg',
    './audio/se/Teleport.ogg',

    './audio/se/Thunder1.ogg',
    './audio/se/Thunder10.ogg',
    './audio/se/Thunder11.ogg',
    './audio/se/Thunder12.ogg',
    './audio/se/Thunder13.ogg',
    './audio/se/Thunder14.ogg',
    './audio/se/Thunder2.ogg',
    './audio/se/Thunder3.ogg',
    './audio/se/Thunder4.ogg',
    './audio/se/Thunder5.ogg',
    './audio/se/Thunder6.ogg',
    './audio/se/Thunder7.ogg',
    './audio/se/Thunder8.ogg',
    './audio/se/Thunder9.ogg',
    './audio/se/Transceiver.ogg',
    './audio/se/Twine.ogg',
    './audio/se/Up1.ogg',
    './audio/se/Up2.ogg',
    './audio/se/Up3.ogg',
    './audio/se/Up4.ogg',
    './audio/se/Up5.ogg',
    './audio/se/Up6.ogg',
    './audio/se/Up7.ogg',
    './audio/se/Up8.ogg',
    './audio/se/Water1.ogg',
    './audio/se/Water2.ogg',
    './audio/se/Water3.ogg',
    './audio/se/Water4.ogg',
    './audio/se/Water5.ogg',
    './audio/se/Wind1.ogg',
    './audio/se/Wind10.ogg',
    './audio/se/Wind11.ogg',
    './audio/se/Wind2.ogg',
    './audio/se/Wind3.ogg',
    './audio/se/Wind4.ogg',
    './audio/se/Wind5.ogg',
    './audio/se/Wind6.ogg',
    './audio/se/Wind7.ogg',
    './audio/se/Wind8.ogg',
    './audio/se/Wind9.ogg',
    './audio/se/Wolf.ogg',

    './characters/MC.json',
    './css/anet.css',
    './css/anet_chat.css',
    './css/game.css',
    './fonts/mplus-1m-regular.woff',
    './fonts/mplus-2p-bold-sub.woff',
    './icon/icon.png',

    './data/Actors.json',
    './data/Animations.json',
    './data/Armors.json',
    './data/Classes.json',
    './data/CommonEvents.json',
    './data/Enemies.json',
    './data/Items.json',
    './data/MapInfos.json',
    './data/Skills.json',
    './data/States.json',
    './data/System.json',
    './data/Tilesets.json',
    './data/Troops.json',
    './data/Weapons.json',
    
    ...Array.from({length: 145}, (_, i) => `./data/Map${String(i + 1).padStart(3, '0')}.json`),

    './effects/Absorb.efkefc',
    './effects/ArrowSpecial.efkefc',
    './effects/BallsOfLight.efkefc',
    './effects/Bind.efkefc',
    './effects/Blind.efkefc',
    './effects/Bodyslam.efkefc',
    './effects/Breath.efkefc',
    './effects/ClawEffect.efkefc',
    './effects/ClawFire.efkefc',
    './effects/ClawIce.efkefc',
    './effects/ClawPhysical.efkefc',
    './effects/ClawSpecial.efkefc',
    './effects/ClawThunder.efkefc',
    './effects/Confusion.efkefc',
    './effects/CureAll1.efkefc',
    './effects/CureAll2.efkefc',
    './effects/CureOne1.efkefc',
    './effects/CureOne2.efkefc',
    './effects/DarknessAll1.efkefc',
    './effects/DarknessAll2.efkefc',
    './effects/DarknessAll3.efkefc',
    './effects/DarknessOne1.efkefc',
    './effects/DarknessOne2.efkefc',
    './effects/Death.efkefc',
    './effects/EarthAll1.efkefc',
    './effects/EarthAll2.efkefc',
    './effects/EarthAll3.efkefc',
    './effects/EarthOne1.efkefc',
    './effects/EarthOne2.efkefc',
    './effects/FireAll1.efkefc',
    './effects/FireAll2.efkefc',
    './effects/FireAll3.efkefc',
    './effects/FireOne1.efkefc',
    './effects/FireOne2.efkefc',
    './effects/Flash.efkefc',
    './effects/Fog.efkefc',
    './effects/GeneralSpecial1.efkefc',
    './effects/GeneralSpecial2.efkefc',
    './effects/HealAll1.efkefc',
    './effects/HealAll2.efkefc',
    './effects/HealOne1.efkefc',
    './effects/HealOne2.efkefc',
    './effects/HitEffect.efkefc',
    './effects/HitFire.efkefc',
    './effects/HitIce.efkefc',
    './effects/HitPhysical.efkefc',
    './effects/HitSpecial1.efkefc',
    './effects/HitSpecial2.efkefc',
    './effects/HitThunder.efkefc',
    './effects/IceAll1.efkefc',
    './effects/IceAll2.efkefc',
    './effects/IceAll3.efkefc',
    './effects/IceOne1.efkefc',
    './effects/IceOne2.efkefc',
    './effects/LaserAll.efkefc',
    './effects/LaserOne.efkefc',
    './effects/LightAll1.efkefc',
    './effects/LightAll2.efkefc',
    './effects/LightAll3.efkefc',
    './effects/LightOne1.efkefc',
    './effects/LightOne2.efkefc',
    './effects/LightPillar1.efkefc',
    './effects/LightPillar2.efkefc',
    './effects/NeutralAll1.efkefc',
    './effects/NeutralAll2.efkefc',
    './effects/NeutralAll3.efkefc',
    './effects/NeutralOne1.efkefc',
    './effects/NeutralOne2.efkefc',
    './effects/Paralyze.efkefc',
    './effects/PierceEffect.efkefc',
    './effects/PierceFire.efkefc',
    './effects/PierceIce.efkefc',
    './effects/PiercePhysical.efkefc',
    './effects/PierceSpecial1.efkefc',
    './effects/PierceSpecial2.efkefc',
    './effects/PierceThunder.efkefc',
    './effects/Poison.efkefc',
    './effects/Pollen.efkefc',
    './effects/Powerdown1.efkefc',
    './effects/Powerdown2.efkefc',
    './effects/Powerdown3.efkefc',
    './effects/Powerup1.efkefc',
    './effects/Powerup2.efkefc',
    './effects/Powerup3.efkefc',
    './effects/Radiation.efkefc',
    './effects/Revive1.efkefc',
    './effects/Revive2.efkefc',
    './effects/ShootAll.efkefc',
    './effects/ShootBarrage.efkefc',
    './effects/ShootNormal.efkefc',
    './effects/ShootSpecial.efkefc',
    './effects/Shout.efkefc',
    './effects/Silence.efkefc',
    './effects/SlashEffect.efkefc',
    './effects/SlashFire.efkefc',
    './effects/SlashIce.efkefc',
    './effects/SlashPhysical.efkefc',
    './effects/SlashSpecial1.efkefc',
    './effects/SlashSpecial2.efkefc',
    './effects/SlashSpecial3.efkefc',
    './effects/SlashThunder.efkefc',
    './effects/Sleep.efkefc',
    './effects/Song.efkefc',
    './effects/SonicWave.efkefc',
    './effects/Sweep.efkefc',
    './effects/ThunderAll1.efkefc',
    './effects/ThunderAll2.efkefc',
    './effects/ThunderAll3.efkefc',
    './effects/ThunderOne1.efkefc',
    './effects/ThunderOne2.efkefc',
    './effects/WaterAll1.efkefc',
    './effects/WaterAll2.efkefc',
    './effects/WaterAll3.efkefc',
    './effects/WaterOne1.efkefc',
    './effects/WaterOne2.efkefc',
    './effects/WindAll1.efkefc',
    './effects/WindAll2.efkefc',
    './effects/WindAll3.efkefc',
    './effects/WindOne1.efkefc',
    './effects/WindOne2.efkefc',

    './effects/Model/Ball.efkmodel',
    './effects/Model/NightHand1.efkmodel',
    './effects/Model/NightHand2.efkmodel',
    './effects/Model/NightHand3.efkmodel',
    './effects/Model/NightHand4.efkmodel',
    './effects/Model/Shield.efkmodel',
    './effects/Model/Skull.efkmodel',
    './effects/Texture/Arrow.png',
    './effects/Texture/Circle.png',
    './effects/Texture/Feather.png',
    './effects/Texture/Flower.png',
    './effects/Texture/Fog.png',
    './effects/Texture/HexCircle.png',
    './effects/Texture/IceRock.png',
    './effects/Texture/LightRing.png',
    './effects/Texture/Line1.png',
    './effects/Texture/Line2.png',
    './effects/Texture/Monster1.png',
    './effects/Texture/Monster2.png',
    './effects/Texture/Monster3.png',
    './effects/Texture/Note1.png',
    './effects/Texture/Note2.png',
    './effects/Texture/Note3.png',
    './effects/Texture/Note4.png',
    './effects/Texture/Particle100.png',
    './effects/Texture/ParticleAlpha.png',
    './effects/Texture/Period.png',
    './effects/Texture/Rhombus1.png',
    './effects/Texture/Rhombus2.png',
    './effects/Texture/Ring.png',
    './effects/Texture/Rock.png',
    './effects/Texture/Shield.png',
    './effects/Texture/ShockWave1.png',
    './effects/Texture/ShockWave2.png',
    './effects/Texture/ShockWaveRing1.png',
    './effects/Texture/ShockWaveRing2.png',
    './effects/Texture/Slash1.png',
    './effects/Texture/Slash2.png',
    './effects/Texture/Snow.png',
    './effects/Texture/Special3_1.png',
    './effects/Texture/Special3_2.png',
    './effects/Texture/Special3_3.png',
    './effects/Texture/Special3_4.png',
    './effects/Texture/Sphere.png',
    './effects/Texture/Spin.png',
    './effects/Texture/Star.png',
    './effects/Texture/Star2.png',
    './effects/Texture/Thorns.png',
    './effects/Texture/ThunderC.png',
    './effects/Texture/ThunderH.png',
    './effects/Texture/ThunderV.png',
    './effects/Texture/Wind.png',
    './effects/Texture/WindMark.png',
    './effects/Texture/WingL.png',
    './effects/Texture/WingR.png',

    './img/Alpha/adminName.png',
    './img/Alpha/nzButton_ChatGroup_All_00.png',
    './img/Alpha/nzButton_ChatGroup_All_01.png',
    './img/Alpha/nzButton_ChatGroup_All_03.png',
    './img/Alpha/nzButton_ChatGroup_Map_00.png',
    './img/Alpha/nzButton_ChatGroup_Map_01.png',
    './img/Alpha/nzButton_ChatGroup_Map_03.png',
    './img/Alpha/nzButton_ChatSendMV_00.png',
    './img/Alpha/nzButton_ChatSendMV_01.png',
    './img/Alpha/nzClickEffect.png',
    './img/Alpha/nzModalNoButton_00.png',
    './img/Alpha/nzModalNoButton_01.png',
    './img/Alpha/nzModalYesButton_00.png',
    './img/Alpha/nzModalYesButton_01.png',
    './img/Alpha/nzTradeButton_00.png',
    './img/Alpha/nzTradeButton_01.png',
    './img/Alpha/nzTradeHeader.png',
    './img/Alpha/nzTradeStatus_NotReady.png',
    './img/Alpha/nzTradeStatus_Ready.png',
    './img/Alpha/nzTradeWindowPortraitBack.png',
    './img/Alpha/PlayerStateIcons.png',
    './img/Alpha/Windows/headerLine.png',
    './img/Alpha/Windows/windowCloseButton_00.png',
    './img/Alpha/Windows/windowCloseButton_01.png',
    './img/Alpha/Windows/windowFrame.png',

    './img/battlebacks1/Castle1.png',
    './img/battlebacks1/Castle2.png',
    './img/battlebacks1/Castle3.png',
    './img/battlebacks1/Clouds.png',
    './img/battlebacks1/Cobblestones1.png',
    './img/battlebacks1/Cobblestones2.png',
    './img/battlebacks1/Cobblestones3.png',
    './img/battlebacks1/Cobblestones4.png',
    './img/battlebacks1/Cobblestones5.png',
    './img/battlebacks1/Colosseum.png',
    './img/battlebacks1/Crystal.png',
    './img/battlebacks1/Cyberspace.png',
    './img/battlebacks1/DecorativeTile1.png',
    './img/battlebacks1/DecorativeTile2.png',
    './img/battlebacks1/DemonCastle1.png',
    './img/battlebacks1/DemonCastle2.png',
    './img/battlebacks1/DemonCastle3.png',
    './img/battlebacks1/DemonicWorld.png',
    './img/battlebacks1/Desert.png',
    './img/battlebacks1/Dirt.png',
    './img/battlebacks1/DirtCave.png',
    './img/battlebacks1/DirtField.png',
    './img/battlebacks1/Fort1.png',
    './img/battlebacks1/Fort2.png',
    './img/battlebacks1/Grassland.png',
    './img/battlebacks1/GrassMaze.png',
    './img/battlebacks1/Ground1.png',
    './img/battlebacks1/Ground2.png',
    './img/battlebacks1/IceCave.png',
    './img/battlebacks1/IceMaze.png',
    './img/battlebacks1/Lava1.png',
    './img/battlebacks1/Lava2.png',
    './img/battlebacks1/LavaCave.png',
    './img/battlebacks1/PoisonSwamp.png',
    './img/battlebacks1/Road1.png',
    './img/battlebacks1/Road2.png',
    './img/battlebacks1/Road3.png',
    './img/battlebacks1/RockCave.png',
    './img/battlebacks1/Sand.png',
    './img/battlebacks1/Ship.png',
    './img/battlebacks1/Smoke.png',
    './img/battlebacks1/Snowfield.png',
    './img/battlebacks1/Space.png',
    './img/battlebacks1/Stone1.png',
    './img/battlebacks1/Stone2.png',
    './img/battlebacks1/Stone3.png',
    './img/battlebacks1/Temple.png',
    './img/battlebacks1/Tent.png',
    './img/battlebacks1/Wasteland.png',
    './img/battlebacks1/Wood1.png',
    './img/battlebacks1/Wood2.png',

    './img/battlebacks2/Brick.png',
    './img/battlebacks2/Bridge.png',
    './img/battlebacks2/Castle1.png',
    './img/battlebacks2/Castle2.png',
    './img/battlebacks2/Castle3.png',
    './img/battlebacks2/Cliff.png',
    './img/battlebacks2/Clouds.png',
    './img/battlebacks2/Colosseum.png',
    './img/battlebacks2/Crystal.png',
    './img/battlebacks2/Cyberspace.png',
    './img/battlebacks2/DarkSpace.png',
    './img/battlebacks2/DemonCastle1.png',
    './img/battlebacks2/DemonCastle2.png',
    './img/battlebacks2/DemonCastle3.png',
    './img/battlebacks2/DemonicWorld.png',
    './img/battlebacks2/Desert.png',
    './img/battlebacks2/DirtCave.png',
    './img/battlebacks2/Forest.png',
    './img/battlebacks2/Fort1.png',
    './img/battlebacks2/Fort2.png',
    './img/battlebacks2/Grassland.png',
    './img/battlebacks2/GrassMaze.png',
    './img/battlebacks2/IceCave.png',
    './img/battlebacks2/IceMaze.png',
    './img/battlebacks2/Lava.png',
    './img/battlebacks2/LavaCave.png',
    './img/battlebacks2/PoisonSwamp.png',
    './img/battlebacks2/Port.png',
    './img/battlebacks2/RockCave.png',
    './img/battlebacks2/Room1.png',
    './img/battlebacks2/Room2.png',
    './img/battlebacks2/Room3.png',
    './img/battlebacks2/Ruins1.png',
    './img/battlebacks2/Ruins2.png',
    './img/battlebacks2/Ruins3.png',
    './img/battlebacks2/Ship.png',
    './img/battlebacks2/Smoke.png',
    './img/battlebacks2/Snowfield.png',
    './img/battlebacks2/Stone1.png',
    './img/battlebacks2/Stone2.png',
    './img/battlebacks2/Stone3.png',
    './img/battlebacks2/Temple.png',
    './img/battlebacks2/Tent.png',
    './img/battlebacks2/Tower.png',
    './img/battlebacks2/Town1.png',
    './img/battlebacks2/Town2.png',
    './img/battlebacks2/Town3.png',
    './img/battlebacks2/Town4.png',
    './img/battlebacks2/Town5.png',
    './img/battlebacks2/Wasteland.png',

    './img/characters/!$Gate1.png',
    './img/characters/!$Gate2.png',
    './img/characters/!$SF_Gate1.png',
    './img/characters/!$SF_Gate2.png',
    './img/characters/!$SF_Gate3.png',
    './img/characters/!Chest.png',
    './img/characters/!Crystal.png',
    './img/characters/!Door1.png',
    './img/characters/!Door2.png',
    './img/characters/!Flame.png',
    './img/characters/!Other1.png',
    './img/characters/!Other2.png',
    './img/characters/!SF_Chest.png',
    './img/characters/!SF_Door1.png',
    './img/characters/!SF_Door2.png',
    './img/characters/!SF_Switch1.png',
    './img/characters/!Switch1.png',
    './img/characters/!Switch2.png',
    './img/characters/!Weapon.png',
    './img/characters/$BigMonster1.png',
    './img/characters/$BigMonster2.png',
    './img/characters/Actor1.png',
    './img/characters/Actor2.png',
    './img/characters/Actor3.png',
    './img/characters/Alpha Damage.png',
    './img/characters/Alpha_Actor.png',
    './img/characters/A_King Walk.png',
    './img/characters/A_King.png',
    './img/characters/Bard Jareth Character.png',
    './img/characters/Bard Jareth Dmg.png',
    './img/characters/Blacksmith Rurik Dmg.png',
    './img/characters/Blacksmith Rurik Stand.png',
    './img/characters/Bron NPC 2.png',
    './img/characters/Bron NPC.png',
    './img/characters/Captain Valerius Character.png',
    './img/characters/Captain Valerius Dmg.png',
    './img/characters/Damage1.png',
    './img/characters/Damage2.png',
    './img/characters/Damage3.png',
    './img/characters/Elara Sorceress Character.png',
    './img/characters/Elara Sorceress dmg.png',
    './img/characters/Elder Tobias Character.png',
    './img/characters/Elder Tobias Dmg.png',
    './img/characters/Evil.png',
    './img/characters/Fenrin Martial Artist Character.png',
    './img/characters/Fenrin Martial Artist dmg.png',
    './img/characters/Garrick Swordsman Character.png',
    './img/characters/Garrick Swordsman dmg.png',
    './img/characters/Hunter Kaela Character.png',
    './img/characters/Hunter Kaela Dmg.png',
    './img/characters/Innkeeper Gorm Character.png',
    './img/characters/Innkeeper Gorm Dmg.png',
    './img/characters/Isolde Priestess Character.png',
    './img/characters/Isolde Priestess dmg.png',
    './img/characters/Kael Knight Character.png',
    './img/characters/Kael Knight dmg.png',
    './img/characters/Knight Character.png',
    './img/characters/Knight Dmg.png',
    './img/characters/Librarian Estel Character.png',
    './img/characters/Librarian Estel Dmg.png',
    './img/characters/Lily Character.png',
    './img/characters/Lily dmg.png',
    './img/characters/Lyra Magic Swordsman Character.png',
    './img/characters/Lyra Magic Swordsman dmg.png',
    './img/characters/Martha Character.png',
    './img/characters/Martha DMG.png',
    './img/characters/MC Character.png',
    './img/characters/MC Laying.png',
    './img/characters/MC sleep.png',
    './img/characters/MC Walking.png',
    './img/characters/Merchant Oryn Laying.png',
    './img/characters/Merchant Oryn Walking.png',
    './img/characters/Mila Char.png',
    './img/characters/Mila Dmg.png',
    './img/characters/Monster.png',
    './img/characters/Nature.png',
    './img/characters/People1.png',
    './img/characters/People2.png',
    './img/characters/People3.png',
    './img/characters/People4.png',
    './img/characters/PortalKeeper Alden Character.png',
    './img/characters/PortalKeeper Alden Dmg.png',
    './img/characters/Priestess Anara Character.png',
    './img/characters/Priestess Anara Dmg.png',
    './img/characters/Professor Haze Character.png',
    './img/characters/Professor Haze Dmg.png',
    './img/characters/SF_Actor1.png',
    './img/characters/SF_Actor2.png',
    './img/characters/SF_Actor3.png',
    './img/characters/SF_Damage1.png',
    './img/characters/SF_Damage2.png',
    './img/characters/SF_Monster.png',
    './img/characters/SF_People1.png',
    './img/characters/SF_People2.png',
    './img/characters/SF_People3.png',
    './img/characters/SF_Vehicle.png',
    './img/characters/Sylas Bandit Character.png',
    './img/characters/Sylas Bandit dmg.png',
    './img/characters/Thorne Hunter Character.png',
    './img/characters/Thorne Hunter dmg.png',
    './img/characters/Vanya DEad.png',
    './img/characters/Vanya Walking And Standing.png',
    './img/characters/Vehicle.png',

    './img/enemies/Actor1_3.png',
    './img/enemies/Actor1_4.png',
    './img/enemies/Actor1_5.png',
    './img/enemies/Actor1_6.png',
    './img/enemies/Actor2_1.png',
    './img/enemies/Actor2_2.png',
    './img/enemies/Actor2_3.png',
    './img/enemies/Actor2_4.png',
    './img/enemies/Actor2_5.png',
    './img/enemies/Actor2_6.png',
    './img/enemies/Actor2_7.png',
    './img/enemies/Actor3_1.png',
    './img/enemies/Actor3_2.png',
    './img/enemies/Actor3_3.png',
    './img/enemies/Actor3_4.png',
    './img/enemies/Berserker.png',
    './img/enemies/Birdman.png',
    './img/enemies/Blackknight.png',
    './img/enemies/Caitsith.png',
    './img/enemies/Captain.png',
    './img/enemies/Crab.png',
    './img/enemies/Crow.png',
    './img/enemies/Darkelf.png',
    './img/enemies/Demon.png',
    './img/enemies/Demoncount.png',
    './img/enemies/Demonpot.png',
    './img/enemies/Demon_metamorphosis.png',
    './img/enemies/Dragon.png',
    './img/enemies/Evilbook.png',
    './img/enemies/Evilgod.png',
    './img/enemies/Foxman.png',
    './img/enemies/Frilledlizard.png',
    './img/enemies/Gatekeeper.png',
    './img/enemies/Gnome.png',
    './img/enemies/Goblin.png',
    './img/enemies/Goddess.png',
    './img/enemies/Goddess_of_death.png',
    './img/enemies/God_of_light.png',
    './img/enemies/Hakutaku.png',
    './img/enemies/Harpy.png',
    './img/enemies/Highking.png',
    './img/enemies/Hi_monster.png',
    './img/enemies/Hydra.png',
    './img/enemies/Ketos.png',
    './img/enemies/Kraken.png',
    './img/enemies/Lich.png',
    './img/enemies/Machinerybee.png',
    './img/enemies/Matango.png',
    './img/enemies/Mechascorpion.png',
    './img/enemies/Medusa.png',
    './img/enemies/Mercenary.png',
    './img/enemies/Mimic.png',
    './img/enemies/Oddegg.png',
    './img/enemies/Petitdevil.png',
    './img/enemies/Plasma.png',
    './img/enemies/Sailor.png',
    './img/enemies/Salamander.png',
    './img/enemies/Sandworm.png',
    './img/enemies/SF_Agent.png',
    './img/enemies/SF_Anaconda.png',
    './img/enemies/SF_Armygorilla.png',
    './img/enemies/SF_Armymonkey.png',
    './img/enemies/SF_Blueogre.png',
    './img/enemies/SF_Boss.png',
    './img/enemies/SF_Brownbear.png',
    './img/enemies/SF_Cyborg.png',
    './img/enemies/SF_Demon_of_universe.png',
    './img/enemies/SF_Drone.png',
    './img/enemies/SF_Enmadaio.png',
    './img/enemies/SF_Evilteddybear.png',
    './img/enemies/SF_Hannyamask.png',
    './img/enemies/SF_Hermit.png',
    './img/enemies/SF_Jiangshi.png',
    './img/enemies/SF_Kamaitachi.png',
    './img/enemies/SF_Kappa.png',
    './img/enemies/SF_Madclown.png',
    './img/enemies/SF_Madscientist.png',
    './img/enemies/SF_Mafia.png',
    './img/enemies/SF_Mechasphere.png',
    './img/enemies/SF_Phoenix.png',
    './img/enemies/SF_Redogre.png',
    './img/enemies/SF_Securityrobot.png',
    './img/enemies/SF_Shadow.png',
    './img/enemies/SF_Skullmask.png',
    './img/enemies/SF_Slaughterrobot.png',
    './img/enemies/SF_Specialforces.png',
    './img/enemies/SF_Talkingmuppet.png',
    './img/enemies/SF_Timebomb.png',
    './img/enemies/SF_Whitewolf.png',
    './img/enemies/SF_Will_o_the_wisp.png',
    './img/enemies/SF_Wolf.png',
    './img/enemies/SF_Workrobot.png',
    './img/enemies/SF_Zombiedog.png',
    './img/enemies/Siren.png',
    './img/enemies/Sorcerer.png',
    './img/enemies/Stoneknight.png',
    './img/enemies/Sylph.png',
    './img/enemies/Tigerbunny.png',
    './img/enemies/Treant.png',
    './img/enemies/Undine.png',
    './img/enemies/Unicorn.png',
    './img/enemies/Witch.png',
    './img/enemies/Wolfman.png',
    './img/enemies/Wraith.png',
    './img/enemies/Zombie.png',

    './img/faces/Actor1.png',
    './img/faces/Actor2.png',
    './img/faces/Actor3.png',
    './img/faces/Alpha.png',
    './img/faces/Azure.png',
    './img/faces/Bard Jareth Face.png',
    './img/faces/Blacksmith Rurik Face.png',
    './img/faces/Bron Face.png',
    './img/faces/Captain Valerius Face.png',
    './img/faces/Elara Sorceress Face.png',
    './img/faces/Elder Tobias Face.png',
    './img/faces/Evil.png',
    './img/faces/Fenrin Martial Artist Face.png',
    './img/faces/Garrick Swordsman Face.png',
    './img/faces/Hunter Kaela Face.png',
    './img/faces/Innkeeper Gorm Face.png',
    './img/faces/Isolde Priestess Face.png',
    './img/faces/Kael Knight Face.png',
    './img/faces/Knight Face.png',
    './img/faces/Librarian Estel Face.png',
    './img/faces/Lily Face.png',
    './img/faces/Lyra Magic Swordsman Face.png',
    './img/faces/Martha Face.png',
    './img/faces/MC Face.png',
    './img/faces/Merchant Oryn Face.png',
    './img/faces/Mila Face.png',
    './img/faces/Monster.png',
    './img/faces/Nature.png',
    './img/faces/People1.png',
    './img/faces/People2.png',
    './img/faces/People3.png',
    './img/faces/People4.png',
    './img/faces/PortalKeeper Alden Face.png',
    './img/faces/Priestess Anara Face.png',
    './img/faces/Professor Haze Face.png',
    './img/faces/SF_Actor1.png',
    './img/faces/SF_Actor2.png',
    './img/faces/SF_Actor3.png',
    './img/faces/SF_Monster.png',
    './img/faces/SF_People1.png',
    './img/faces/Sylas Bandit Face.png',
    './img/faces/Thorne Hunter Face.png',
    './img/faces/Vanya Face.png',

    './img/parallaxes/BlueSky.png',
    './img/parallaxes/Clouds.png',
    './img/parallaxes/DarkClouds.png',
    './img/parallaxes/DarkSpace.png',
    './img/parallaxes/Desert.png',
    './img/parallaxes/DesertNight.png',
    './img/parallaxes/Forest.png',
    './img/parallaxes/IslandofSky1.png',
    './img/parallaxes/IslandofSky2.png',
    './img/parallaxes/Lava.png',
    './img/parallaxes/Mountains1.png',
    './img/parallaxes/Mountains2.png',
    './img/parallaxes/Mountains3.png',
    './img/parallaxes/Ocean.png',
    './img/parallaxes/RedSky.png',
    './img/parallaxes/River.png',
    './img/parallaxes/SnowForest.png',
    './img/parallaxes/Space.png',
    './img/parallaxes/StarlitSky.png',
    './img/parallaxes/Twilight.png',
    './img/parallaxes/Universe.png',

    './img/pictures/Actor1_1.png',
    './img/pictures/Actor1_2.png',
    './img/pictures/Actor1_3.png',
    './img/pictures/Actor1_4.png',
    './img/pictures/Actor1_5.png',
    './img/pictures/Actor1_6.png',
    './img/pictures/Actor1_7.png',
    './img/pictures/Actor1_8.png',
    './img/pictures/Actor2_1.png',
    './img/pictures/Actor2_2.png',
    './img/pictures/Actor2_3.png',
    './img/pictures/Actor2_4.png',
    './img/pictures/Actor2_5.png',
    './img/pictures/Actor2_6.png',
    './img/pictures/Actor2_7.png',
    './img/pictures/Actor2_8.png',
    './img/pictures/Actor3_1.png',
    './img/pictures/Actor3_2.png',
    './img/pictures/Actor3_3.png',
    './img/pictures/Actor3_4.png',
    './img/pictures/Actor3_5.png',
    './img/pictures/Actor3_6.png',
    './img/pictures/Actor3_7.png',
    './img/pictures/Actor3_8.png',
    './img/pictures/Evil_1.png',
    './img/pictures/Evil_2.png',
    './img/pictures/Evil_3.png',
    './img/pictures/Evil_4.png',
    './img/pictures/Evil_5.png',
    './img/pictures/Evil_6.png',
    './img/pictures/Evil_7.png',
    './img/pictures/Evil_8.png',
    './img/pictures/Monster_1.png',
    './img/pictures/Monster_2.png',
    './img/pictures/Monster_3.png',
    './img/pictures/Monster_4.png',
    './img/pictures/Monster_5.png',
    './img/pictures/Monster_6.png',
    './img/pictures/Monster_7.png',
    './img/pictures/Monster_8.png',
    './img/pictures/Nature_1.png',
    './img/pictures/Nature_2.png',
    './img/pictures/Nature_3.png',
    './img/pictures/Nature_4.png',
    './img/pictures/Nature_5.png',
    './img/pictures/Nature_6.png',
    './img/pictures/Nature_7.png',
    './img/pictures/Nature_8.png',
    './img/pictures/People1_1.png',
    './img/pictures/People1_2.png',
    './img/pictures/People1_3.png',
    './img/pictures/People1_4.png',
    './img/pictures/People1_5.png',
    './img/pictures/People1_6.png',
    './img/pictures/People1_7.png',
    './img/pictures/People1_8.png',
    './img/pictures/People2_1.png',
    './img/pictures/People2_2.png',
    './img/pictures/People2_3.png',
    './img/pictures/People2_4.png',
    './img/pictures/People2_5.png',
    './img/pictures/People2_6.png',
    './img/pictures/People2_7.png',
    './img/pictures/People2_8.png',
    './img/pictures/People3_1.png',
    './img/pictures/People3_2.png',
    './img/pictures/People3_3.png',
    './img/pictures/People3_4.png',
    './img/pictures/People3_5.png',
    './img/pictures/People3_6.png',
    './img/pictures/People3_7.png',
    './img/pictures/People3_8.png',
    './img/pictures/People4_1.png',
    './img/pictures/People4_2.png',
    './img/pictures/People4_3.png',
    './img/pictures/People4_4.png',
    './img/pictures/People4_5.png',
    './img/pictures/People4_6.png',
    './img/pictures/People4_7.png',
    './img/pictures/People4_8.png',
    './img/pictures/SF_Actor1_1.png',
    './img/pictures/SF_Actor1_2.png',
    './img/pictures/SF_Actor1_3.png',
    './img/pictures/SF_Actor1_4.png',
    './img/pictures/SF_Actor1_5.png',
    './img/pictures/SF_Actor1_6.png',
    './img/pictures/SF_Actor1_7.png',
    './img/pictures/SF_Actor1_8.png',
    './img/pictures/SF_Actor2_1.png',
    './img/pictures/SF_Actor2_2.png',
    './img/pictures/SF_Actor2_3.png',
    './img/pictures/SF_Actor2_4.png',
    './img/pictures/SF_Actor2_5.png',
    './img/pictures/SF_Actor2_6.png',
    './img/pictures/SF_Actor2_7.png',
    './img/pictures/SF_Actor2_8.png',
    './img/pictures/SF_Actor3_1.png',
    './img/pictures/SF_Actor3_2.png',
    './img/pictures/SF_Actor3_3.png',
    './img/pictures/SF_Actor3_4.png',
    './img/pictures/SF_Actor3_5.png',
    './img/pictures/SF_Actor3_6.png',
    './img/pictures/SF_Actor3_7.png',
    './img/pictures/SF_Actor3_8.png',
    './img/pictures/SF_Monster_1.png',
    './img/pictures/SF_Monster_2.png',
    './img/pictures/SF_Monster_3.png',
    './img/pictures/SF_Monster_4.png',
    './img/pictures/SF_Monster_5.png',
    './img/pictures/SF_Monster_6.png',
    './img/pictures/SF_Monster_7.png',
    './img/pictures/SF_Monster_8.png',
    './img/pictures/SF_People1_1.png',
    './img/pictures/SF_People1_2.png',
    './img/pictures/SF_People1_3.png',
    './img/pictures/SF_People1_4.png',
    './img/pictures/SF_People1_5.png',
    './img/pictures/SF_People1_6.png',
    './img/pictures/SF_People1_7.png',
    './img/pictures/SF_People1_8.png',

    './img/sv_actors/Actor1_1.png',
    './img/sv_actors/Actor1_2.png',
    './img/sv_actors/Actor1_3.png',
    './img/sv_actors/Actor1_4.png',
    './img/sv_actors/Actor1_5.png',
    './img/sv_actors/Actor1_6.png',
    './img/sv_actors/Actor1_7.png',
    './img/sv_actors/Actor1_8.png',
    './img/sv_actors/Actor2_1.png',
    './img/sv_actors/Actor2_2.png',
    './img/sv_actors/Actor2_3.png',
    './img/sv_actors/Actor2_4.png',
    './img/sv_actors/Actor2_5.png',
    './img/sv_actors/Actor2_6.png',
    './img/sv_actors/Actor2_7.png',
    './img/sv_actors/Actor2_8.png',
    './img/sv_actors/Actor3_5.png',
    './img/sv_actors/Actor3_6.png',
    './img/sv_actors/Actor3_7.png',
    './img/sv_actors/Actor3_8.png',
    './img/sv_actors/A_Test.png',
    './img/sv_actors/Bard Jareth Battler.png',
    './img/sv_actors/Battller.png',
    './img/sv_actors/Blacksmith Rurik Battler.png',
    './img/sv_actors/Bron Battler.png',
    './img/sv_actors/Captain Valerius Battler.png',
    './img/sv_actors/Elara Sorceress Battler.png',
    './img/sv_actors/Elder Tobias Battler.png',
    './img/sv_actors/Fenrin Martial Artist Battler.png',
    './img/sv_actors/Garrick Swordsman Battler.png',
    './img/sv_actors/Hunter Kaela Battler.png',
    './img/sv_actors/Innkeeper Gorm Battler.png',
    './img/sv_actors/Isolde Priestess Battler.png',
    './img/sv_actors/Kael Knight Battler.png',
    './img/sv_actors/Knight Battler.png',
    './img/sv_actors/Librarian Estel Battler.png',
    './img/sv_actors/Lily battler.png',
    './img/sv_actors/Lyra Magic Swordsman Battler.png',
    './img/sv_actors/Martha Battler.png',
    './img/sv_actors/MC Batler.png',
    './img/sv_actors/MC Battler.png',
    './img/sv_actors/Merchant Oryn Battler.png',
    './img/sv_actors/MIla Battler.png',
    './img/sv_actors/PortalKeeper Alden Battler.png',
    './img/sv_actors/Priestess Anara Battler.png',
    './img/sv_actors/Professor Haze Battler.png',
    './img/sv_actors/SF_Actor1_1.png',
    './img/sv_actors/SF_Actor1_2.png',
    './img/sv_actors/SF_Actor1_3.png',
    './img/sv_actors/SF_Actor1_4.png',
    './img/sv_actors/SF_Actor1_5.png',
    './img/sv_actors/SF_Actor1_6.png',
    './img/sv_actors/SF_Actor1_7.png',
    './img/sv_actors/SF_Actor1_8.png',
    './img/sv_actors/SF_Actor2_1.png',
    './img/sv_actors/SF_Actor2_2.png',
    './img/sv_actors/SF_Actor2_3.png',
    './img/sv_actors/SF_Actor2_4.png',
    './img/sv_actors/SF_Actor2_5.png',
    './img/sv_actors/SF_Actor2_6.png',
    './img/sv_actors/SF_Actor2_7.png',
    './img/sv_actors/SF_Actor2_8.png',
    './img/sv_actors/SF_Actor3_5.png',
    './img/sv_actors/SF_Actor3_6.png',
    './img/sv_actors/SF_Actor3_7.png',
    './img/sv_actors/SF_Actor3_8.png',
    './img/sv_actors/Sylas Bandit Battler.png',
    './img/sv_actors/Thorne Hunter Battler.png',
    './img/sv_actors/Vanya Battler.png',

    './img/sv_enemies/Actor1_3.png',
    './img/sv_enemies/Actor1_4.png',
    './img/sv_enemies/Actor1_5.png',
    './img/sv_enemies/Actor1_6.png',
    './img/sv_enemies/Actor2_1.png',
    './img/sv_enemies/Actor2_2.png',
    './img/sv_enemies/Actor2_3.png',
    './img/sv_enemies/Actor2_4.png',
    './img/sv_enemies/Actor2_5.png',
    './img/sv_enemies/Actor2_6.png',
    './img/sv_enemies/Actor2_7.png',
    './img/sv_enemies/Actor3_1.png',
    './img/sv_enemies/Actor3_2.png',
    './img/sv_enemies/Actor3_3.png',
    './img/sv_enemies/Actor3_4.png',
    './img/sv_enemies/AncientAutomaton.png',
    './img/sv_enemies/Arcane Crystal Magic Circle.png',
    './img/sv_enemies/Arcane Crystal.png',
    './img/sv_enemies/Arcane Golem.png',
    './img/sv_enemies/Arcane Orb Fire.png',
    './img/sv_enemies/Arcane Orb Frost.png',
    './img/sv_enemies/Arcane Orb Thunder.png',
    './img/sv_enemies/Arcane Orb Wind.png',
    './img/sv_enemies/Aspiring Knight Gladius.png',
    './img/sv_enemies/Aspiring Knight Palazo.png',
    './img/sv_enemies/Aspiring Knight Valterra.png',
    './img/sv_enemies/Assasin Garland.png',
    './img/sv_enemies/Assembling Automatons Automaton A.png',
    './img/sv_enemies/Assembling Automatons Automaton B.png',
    './img/sv_enemies/Assembling Automatons Automaton C.png',
    './img/sv_enemies/Assembling Automatons Automaton D.png',
    './img/sv_enemies/Berserker.png',
    './img/sv_enemies/Birdman.png',
    './img/sv_enemies/Blackknight.png',
    './img/sv_enemies/Blood Manipulation Feral.png',
    './img/sv_enemies/Blood Manipulation Mage.png',
    './img/sv_enemies/Blood Manipulation Slime.png',
    './img/sv_enemies/Boss Abomination Aqua.png',
    './img/sv_enemies/Boss Abomination Red.png',
    './img/sv_enemies/Boss Alfadriel.png',
    './img/sv_enemies/Boss Ancient Automaton.png',
    './img/sv_enemies/Boss Ancient Priestess.png',
    './img/sv_enemies/Boss Astral Lich.png',
    './img/sv_enemies/Boss Big Fish.png',
    './img/sv_enemies/Boss Black Ant Queen.png',
    './img/sv_enemies/Boss Blood Feral.png',
    './img/sv_enemies/Boss Bonemask Shadow Creature.png',
    './img/sv_enemies/Boss Continental Turtle Rukkha.png',
    './img/sv_enemies/Boss Crab King Karkinos.png',
    './img/sv_enemies/Boss Daidarabotchi.png',
    './img/sv_enemies/Boss Dark Queen Shaccad Yoggoth.png',
    './img/sv_enemies/Boss Darklord Excelsios.png',
    './img/sv_enemies/Boss Darkness Titan Ilnoct.png',
    './img/sv_enemies/Boss Doppelganger Slime.png',
    './img/sv_enemies/Boss Dragon Emperor.png',
    './img/sv_enemies/Boss Dragon Huanglong.png',
    './img/sv_enemies/Boss Dryad Queen Rafflesia.png',
    './img/sv_enemies/Boss Dryad Yggdrasil.png',
    './img/sv_enemies/Boss Earth Dragon.png',
    './img/sv_enemies/Boss Eldritch God Shaccad\'Yoggoth.png',
    './img/sv_enemies/Boss Eldritch Slime Overmind.png',
    './img/sv_enemies/Boss Feral Kitsune.png',
    './img/sv_enemies/Boss Flynn The Original Slime.png',
    './img/sv_enemies/Boss God Jupiter.png',
    './img/sv_enemies/Boss God Novus.png',
    './img/sv_enemies/Boss God Warrior Dagon.png',
    './img/sv_enemies/Boss God Warrior Isis.png',
    './img/sv_enemies/Boss God Warrior Osiris.png',
    './img/sv_enemies/Boss God Warrior Poseidon.png',
    './img/sv_enemies/Boss God Warrior Skoll.png',
    './img/sv_enemies/Boss Goddess Aphrodite.png',
    './img/sv_enemies/Boss Goddess Innova.png',
    './img/sv_enemies/Boss Grand Sorceress Duessa.png',
    './img/sv_enemies/Boss Hades.png',
    './img/sv_enemies/Boss Hellhound Garm.png',
    './img/sv_enemies/Boss Ice Titan Demeres.png',
    './img/sv_enemies/Boss Insect Queen.png',
    './img/sv_enemies/Boss Jubokko.png',
    './img/sv_enemies/Boss Khronos.png',
    './img/sv_enemies/Boss Legendary Knight Remment.png',
    './img/sv_enemies/Boss Lich King.png',
    './img/sv_enemies/Boss Life Titan Aphylia.png',
    './img/sv_enemies/Boss Light Titan Alfadriel.png',
    './img/sv_enemies/Boss Living Hoard Midas.png',
    './img/sv_enemies/Boss Mecha Rattlesnake.png',
    './img/sv_enemies/Boss Mecha-Dragon Ladon.png',
    './img/sv_enemies/Boss Mecha-Scorpion.png',
    './img/sv_enemies/Boss Mythical Knight Goldnharl.png',
    './img/sv_enemies/Boss Nature Titan Tellia.png',
    './img/sv_enemies/Boss Nuckelavee.png',
    './img/sv_enemies/Boss Orc Chief Grunt.png',
    './img/sv_enemies/Boss Parrot King.png',
    './img/sv_enemies/Boss Radulac The Voidvod.png',
    './img/sv_enemies/Boss Reaper Nihilo.png',
    './img/sv_enemies/Boss Runic Stone Golem Goliath.png',
    './img/sv_enemies/Boss Sea Calamity Urmica.png',
    './img/sv_enemies/Boss Sea Dragon Leviathan.png',
    './img/sv_enemies/Boss Sea Mermaid Warrior Undeen.png',
    './img/sv_enemies/Boss Skull Knight Xoer.png',
    './img/sv_enemies/Boss Slime Golem.png',

    './img/sv_enemies/Boss Son Of Valhalla.png',
    './img/sv_enemies/Boss Spirit Fighter.png',
    './img/sv_enemies/Boss Sun Goddess.png',
    './img/sv_enemies/Boss Tantalus.png',
    './img/sv_enemies/Boss Thanatos.png',
    './img/sv_enemies/Boss The Fallen.png',
    './img/sv_enemies/Boss The Horde.png',
    './img/sv_enemies/Boss The Originator.png',
    './img/sv_enemies/Boss Thunder Titan Dynamo.png',
    './img/sv_enemies/Boss Tiamat Unleashed.png',
    './img/sv_enemies/Boss Tiamat.png',
    './img/sv_enemies/Boss Twin Gods.png',
    './img/sv_enemies/Boss Void Gargoyle Sabre.png',
    './img/sv_enemies/Boss Wind Titan Ventoss.png',
    './img/sv_enemies/Boss Zeograth.png',
    './img/sv_enemies/Boss Zodiac Cancer.png',
    './img/sv_enemies/Breakfast Nightmares Bacon Beast.png',
    './img/sv_enemies/Breakfast Nightmares Bread Loaf.png',
    './img/sv_enemies/Breakfast Nightmares Egg Slime.png',
    './img/sv_enemies/Caitsith.png',
    './img/sv_enemies/Captain.png',
    './img/sv_enemies/Cave Dweller Blind Dragon.png',
    './img/sv_enemies/Cave Dweller Rock Mimic.png',
    './img/sv_enemies/Cave Dweller Worm.png',
    './img/sv_enemies/Celestial Beatrix.png',
    './img/sv_enemies/Cerberus Ptolemaios.png',
    './img/sv_enemies/Clockwork Abomination.png',
    './img/sv_enemies/Clockwork Aerial.png',
    './img/sv_enemies/Clockwork Dragon Juggernaut.png',
    './img/sv_enemies/Clockwork Dragon.png',
    './img/sv_enemies/Clockwork Gigas.png',
    './img/sv_enemies/Clockwork Iron Maiden.png',
    './img/sv_enemies/Clockwork Juggernaut.png',
    './img/sv_enemies/Clockwork King.png',
    './img/sv_enemies/Clockwork Knight B.png',
    './img/sv_enemies/Clockwork Knight C.png',
    './img/sv_enemies/Clockwork Knight D.png',
    './img/sv_enemies/Clockwork Mini A.png',
    './img/sv_enemies/Clockwork Mini B.png',
    './img/sv_enemies/Clockwork Mini C.png',
    './img/sv_enemies/Clockwork Prototype.png',
    './img/sv_enemies/Clockwork Queen.png',
    './img/sv_enemies/Clockwork Reaper.png',
    './img/sv_enemies/Clockwork Skull.png',
    './img/sv_enemies/Clockwork Slime.png',
    './img/sv_enemies/Clockwork Spider Mini.png',
    './img/sv_enemies/Clockwork Spider.png',
    './img/sv_enemies/Colossal Bat.png',
    './img/sv_enemies/Colossal Dark Crow.png',
    './img/sv_enemies/Colossal Hydra 1.png',
    './img/sv_enemies/Colossal Hydra 2.png',
    './img/sv_enemies/Colossal Hydra 3.png',
    './img/sv_enemies/Colossal Scorpion.png',
    './img/sv_enemies/Colossal Snake Black.png',
    './img/sv_enemies/Colossal Snake Red.png',
    './img/sv_enemies/Colossal Snake.png',
    './img/sv_enemies/Colossal T-Rex Black.png',
    './img/sv_enemies/Colossal T-Rex Orange.png',
    './img/sv_enemies/Colossal T-Rex Red.png',
    './img/sv_enemies/Corrupted Fire Wolf.png',
    './img/sv_enemies/Corrupted Ice Mantis B.png',
    './img/sv_enemies/Corrupted Ice Mantis.png',
    './img/sv_enemies/Corrupted Stone Bear.png',
    './img/sv_enemies/Corrupted Void Fire Wolf.png',
    './img/sv_enemies/Crab.png',
    './img/sv_enemies/Crocodile Warriors Mage.png',
    './img/sv_enemies/Crocodile Warriors Paladin.png',
    './img/sv_enemies/Crocodile Warriors Rogue.png',
    './img/sv_enemies/Crow.png',
    './img/sv_enemies/Crystal Golem.png',
    './img/sv_enemies/Cyber Blader.png',
    './img/sv_enemies/Cyber Hawk.png',
    './img/sv_enemies/Cyber Ogre.png',
    './img/sv_enemies/Cyber Pegasus.png',
    './img/sv_enemies/Cyber Slime.png',
    './img/sv_enemies/Cybermancer.png',
    './img/sv_enemies/Dark Elves Axe Warrior.png',
    './img/sv_enemies/Dark Elves Crystal Mage.png',
    './img/sv_enemies/Dark Elves Healer Priestess.png',
    './img/sv_enemies/Darkelf.png',
    './img/sv_enemies/Darkness Angel Reaper.png',
    './img/sv_enemies/Darkness Angel.png',
    './img/sv_enemies/Darkness Banshee.png',
    './img/sv_enemies/Darkness Behemoth.png',
    './img/sv_enemies/Darkness Blade Colossus.png',
    './img/sv_enemies/Darkness Blade Reaper.png',
    './img/sv_enemies/Darkness Cultist Mage.png',
    './img/sv_enemies/Darkness Devilimp.png',
    './img/sv_enemies/Darkness Drakenvamp.png',
    './img/sv_enemies/Darkness Dullahan.png',

    './img/sv_enemies/Darkness Flame.png',
    './img/sv_enemies/Darkness Gargoyle Atrox.png',
    './img/sv_enemies/Darkness Hound Inferni.png',
    './img/sv_enemies/Darkness Imp.png',
    './img/sv_enemies/Darkness Knight Magellan.png',
    './img/sv_enemies/Darkness Lord Knight.png',
    './img/sv_enemies/Darkness Oculus.png',
    './img/sv_enemies/Darkness Ogre.png',
    './img/sv_enemies/Darkness Reaper.png',
    './img/sv_enemies/Darkness Seeker.png',
    './img/sv_enemies/Darkness Slime GhastMallow.png',
    './img/sv_enemies/Darkness Slime.png',
    './img/sv_enemies/Darkness Succubus Lariatt.png',
    './img/sv_enemies/Darkness Succubus.png',
    './img/sv_enemies/Darkness Wisp.png',
    './img/sv_enemies/Demon.png',
    './img/sv_enemies/Demoncount.png',
    './img/sv_enemies/Demonpot.png',
    './img/sv_enemies/Demon_metamorphosis.png',
    './img/sv_enemies/Desert Cactus Triple.png',
    './img/sv_enemies/Desert Feral Cactus.png',
    './img/sv_enemies/Desert Parasand.png',
    './img/sv_enemies/Desert Rock Bunny.png',
    './img/sv_enemies/Desert Rock Lizard.png',
    './img/sv_enemies/Desert Sand Snake.png',
    './img/sv_enemies/Desert Sand Tentacle.png',
    './img/sv_enemies/Dragon Black.png',
    './img/sv_enemies/Dragon Dark King.png',
    './img/sv_enemies/Dragon Egg A.png',
    './img/sv_enemies/Dragon Egg B.png',
    './img/sv_enemies/Dragon Egg C.png',
    './img/sv_enemies/Dragon Egg D.png',
    './img/sv_enemies/Dragon Egg E.png',
    './img/sv_enemies/Dragon Emperor Zalaras.png',
    './img/sv_enemies/Dragon Green.png',
    './img/sv_enemies/Dragon King Blue.png',
    './img/sv_enemies/Dragon King Brown.png',
    './img/sv_enemies/Dragon King Green.png',
    './img/sv_enemies/Dragon King Red.png',
    './img/sv_enemies/Dragon Lord A.png',
    './img/sv_enemies/Dragon Lord B.png',
    './img/sv_enemies/Dragon Oriental Dragon.png',
    './img/sv_enemies/Dragon Red.png',
    './img/sv_enemies/Dragon Triple Head Darkness.png',
    './img/sv_enemies/Dragon Triple Head Venom.png',
    './img/sv_enemies/Dragon White King.png',
    './img/sv_enemies/Dragon Wyrm.png',
    './img/sv_enemies/Dragon Wyvern Blue.png',
    './img/sv_enemies/Dragon Wyvern Brown.png',
    './img/sv_enemies/Dragon Wyvern Green.png',
    './img/sv_enemies/Dragon Wyvern Red.png',
    './img/sv_enemies/Dragon.png',
    './img/sv_enemies/Dragons Hydra.png',
    './img/sv_enemies/Dragons Scarlet Wyrm.png',
    './img/sv_enemies/Dragons Sea Dragon.png',
    './img/sv_enemies/Dryads Archer.png',
    './img/sv_enemies/Dryads Mage.png',
    './img/sv_enemies/Dryads Warrior.png',
    './img/sv_enemies/Dwarf Axe Warrior.png',
    './img/sv_enemies/Dwarf Dragon Slayer.png',
    './img/sv_enemies/Dwarf Drill Knight.png',
    './img/sv_enemies/Earth Bull.png',
    './img/sv_enemies/Earth Bush Wisp.png',
    './img/sv_enemies/Earth Gemstone Golem.png',
    './img/sv_enemies/Earth Leaf Imp.png',
    './img/sv_enemies/Earth Lion.png',
    './img/sv_enemies/Earth Mandrake.png',
    './img/sv_enemies/Earth Rock Golem.png',
    './img/sv_enemies/Earth Snake.png',
    './img/sv_enemies/Earth Spawn.png',
    './img/sv_enemies/Earth Turtle.png',
    './img/sv_enemies/Earth Wisp.png',
    './img/sv_enemies/Egypt Archer.png',
    './img/sv_enemies/Egypt Axe.png',
    './img/sv_enemies/Egypt Chariot.png',
    './img/sv_enemies/Egypt Cobra.png',
    './img/sv_enemies/Egypt Crocodile.png',
    './img/sv_enemies/Egypt Hieracosphinx.png',
    './img/sv_enemies/Egypt Knight.png',
    './img/sv_enemies/Egypt Mage.png',
    './img/sv_enemies/Egypt Mummy A.png',
    './img/sv_enemies/Egypt Mummy B.png',
    './img/sv_enemies/Egypt Mummy C.png',
    './img/sv_enemies/Egypt Sphinx Big.png',
    './img/sv_enemies/Egypt Sphinx Small.png',
    './img/sv_enemies/Eldritch Abomination Gazer.png',
    './img/sv_enemies/Eldritch Abomination Hound.png',

    './img/sv_enemies/Eldritch Abomination Tyrant.png',
    './img/sv_enemies/Eldritch Abominations Abyss Denizen.png',
    './img/sv_enemies/Eldritch Abominations Scout.png',
    './img/sv_enemies/Eldritch Abominations Ultimate.png',
    './img/sv_enemies/Eldritch Fire Slimei.png',
    './img/sv_enemies/Eldritch Fire Slimeii.png',
    './img/sv_enemies/Eldritch Fire Slimeiii.png',
    './img/sv_enemies/Eldritch Gazer Merem.png',
    './img/sv_enemies/Eldritch Gazer Velz.png',
    './img/sv_enemies/Eldritch God ShacadYoggoth.png',
    './img/sv_enemies/Eldritch Ice Slimei.png',
    './img/sv_enemies/Eldritch Ice Slimeii.png',
    './img/sv_enemies/Eldritch Ice Slimeiii.png',
    './img/sv_enemies/Eldritch Slime A.png',
    './img/sv_enemies/Eldritch Slime B.png',
    './img/sv_enemies/Eldritch Slime Cerulean.png',
    './img/sv_enemies/Eldritch Slime Spawn A.png',
    './img/sv_enemies/Eldritch Slime Spawn B.png',
    './img/sv_enemies/Eldritch Slime Spawn C.png',
    './img/sv_enemies/Eldritch Slime Spawn D.png',
    './img/sv_enemies/Eldritch Slime Spawn E.png',
    './img/sv_enemies/Eldritch Slime Vermillion.png',
    './img/sv_enemies/Eldritch Slime Viridian.png',
    './img/sv_enemies/Elemental Earth Spirit Tellia.png',
    './img/sv_enemies/Elemental Gemstone Earth.png',
    './img/sv_enemies/Elemental Gemstone Fire.png',
    './img/sv_enemies/Elemental Gemstone Thunder.png',
    './img/sv_enemies/Elemental Gemstone Water.png',
    './img/sv_enemies/Elemental Gemstone Wind.png',
    './img/sv_enemies/Elemental Goddess Forest Flora.png',
    './img/sv_enemies/Elemental Goddess Ice Yukia.png',
    './img/sv_enemies/Elemental Goddess Wind Airi.png',
    './img/sv_enemies/Elemental Ice Spirit Helida.png',
    './img/sv_enemies/Elemental Spirit Fire Blazia.png',
    './img/sv_enemies/Elemental Titan Aphylia.png',
    './img/sv_enemies/Elemental Titan Aquos.png',
    './img/sv_enemies/Elemental Titan Ignis.png',
    './img/sv_enemies/Elemental Titan Tellia.png',
    './img/sv_enemies/Elemental Titan Terran.png',
    './img/sv_enemies/Elemental Titan Ventoss.png',
    './img/sv_enemies/Elemental Wind Spirit Tempestia.png',
    './img/sv_enemies/Elf_Archer.png',
    './img/sv_enemies/Elf_Assasin.png',
    './img/sv_enemies/Elf_Knight_Crossbow.png',
    './img/sv_enemies/Elf_Knight_Dual.png',
    './img/sv_enemies/Elf_Knight_Mage.png',
    './img/sv_enemies/Elf_Knight_Spear.png',
    './img/sv_enemies/Elf_Knight_Sword.png',
    './img/sv_enemies/Elves Nature Linker.png',
    './img/sv_enemies/Elves Rogue Elf.png',
    './img/sv_enemies/Elves Spellcaster.png',
    './img/sv_enemies/Evilbook.png',
    './img/sv_enemies/Evilgod.png',
    './img/sv_enemies/Fallen Dragon Knight.png',
    './img/sv_enemies/Fallen Great Sword.png',
    './img/sv_enemies/Fallen Winged Sword.png',
    './img/sv_enemies/Fire Bull.png',
    './img/sv_enemies/Fire Dragonspawn.png',
    './img/sv_enemies/Fire Elemental  Imp.png',
    './img/sv_enemies/Fire Elemental Angel.png',
    './img/sv_enemies/Fire Elemental Bat.png',
    './img/sv_enemies/Fire Kindred Flame.png',
    './img/sv_enemies/Fire Lava Spawn.png',
    './img/sv_enemies/Fire Lava Worm.png',
    './img/sv_enemies/Fire Lion.png',
    './img/sv_enemies/Fire Minivolcano.png',
    './img/sv_enemies/Fire Ogre.png',
    './img/sv_enemies/Fire Pumice Rock.png',
    './img/sv_enemies/Fire Pumice Sheep.png',
    './img/sv_enemies/Fire Sabretooth.png',
    './img/sv_enemies/Fire Salamander.png',
    './img/sv_enemies/Fire Snake.png',
    './img/sv_enemies/FIre Toad.png',
    './img/sv_enemies/Fire Turtle.png',
    './img/sv_enemies/Fire Volcanic Golem.png',
    './img/sv_enemies/Fire Volcanic Maiden.png',
    './img/sv_enemies/Fire Vulture.png',
    './img/sv_enemies/Fire Wisp.png',
    './img/sv_enemies/Flame Knight.png',
    './img/sv_enemies/Forest Blue Flower.png',
    './img/sv_enemies/Forest Catermoth.png',
    './img/sv_enemies/Forest Darkluff.png',
    './img/sv_enemies/Forest Deer.png',
    './img/sv_enemies/Forest Fairy Dragon Xinbal.png',
    './img/sv_enemies/Forest Fairy Filia.png',
    './img/sv_enemies/Forest Fangrot.png',
    './img/sv_enemies/Forest Golem.png',
    './img/sv_enemies/Forest Grasshopper.png',

    './img/sv_enemies/Forest Green Spider.png',
    './img/sv_enemies/Forest Imperial Widow.png',
    './img/sv_enemies/Forest Kawabun.png',
    './img/sv_enemies/Forest Mobun.png',
    './img/sv_enemies/Forest Mothy.png',
    './img/sv_enemies/Forest Noxluff.png',
    './img/sv_enemies/Forest Ogre Orkgre.png',
    './img/sv_enemies/Forest Panda.png',
    './img/sv_enemies/Forest Pink Flower.png',
    './img/sv_enemies/Forest Red Flower.png',
    './img/sv_enemies/Forest Red Spider.png',
    './img/sv_enemies/Forest Shroom.png',
    './img/sv_enemies/Forest Shroomy.png',
    './img/sv_enemies/Forest Spider.png',
    './img/sv_enemies/Forest Spora.png',
    './img/sv_enemies/Forest Sprout.png',
    './img/sv_enemies/Forest Tree.png',
    './img/sv_enemies/Forest Uzu.png',
    './img/sv_enemies/Forest White Flower.png',
    './img/sv_enemies/Foxman.png',
    './img/sv_enemies/Frilledlizard.png',
    './img/sv_enemies/Gargoyle Grifos.png',
    './img/sv_enemies/Garuda Garunix.png',
    './img/sv_enemies/Gatekeeper.png',
    './img/sv_enemies/Gazers Eyewing.png',
    './img/sv_enemies/Gazers Skull.png',
    './img/sv_enemies/Gazers Tenteye.png',
    './img/sv_enemies/Ghost Ghostus.png',
    './img/sv_enemies/Ghost Knight Destrand.png',
    './img/sv_enemies/Ghost Knight Galpha.png',
    './img/sv_enemies/Ghost Knight Goliath.png',
    './img/sv_enemies/Ghost Puppet Pailo.png',
    './img/sv_enemies/Ghost Revelator.png',
    './img/sv_enemies/Gnome.png',
    './img/sv_enemies/Goblin Archer.png',
    './img/sv_enemies/Goblin Elite.png',
    './img/sv_enemies/Goblin Grunt.png',
    './img/sv_enemies/Goblin Mage.png',
    './img/sv_enemies/Goblin Raider.png',
    './img/sv_enemies/Goblin.png',
    './img/sv_enemies/God Novus.png',
    './img/sv_enemies/Goddess Innova.png',
    './img/sv_enemies/Goddess.png',
    './img/sv_enemies/Goddess_of_death.png',
    './img/sv_enemies/God_of_light.png',
    './img/sv_enemies/Gunblin Gibson.png',
    './img/sv_enemies/Gunblin Jackson.png',
    './img/sv_enemies/Gunblin Schecter.png',
    './img/sv_enemies/Hakutaku.png',
    './img/sv_enemies/Halloween Bat.png',
    './img/sv_enemies/Halloween Black Cat.png',
    './img/sv_enemies/Halloween Dagger skeleton.png',
    './img/sv_enemies/Halloween Lick O Wisp.png',
    './img/sv_enemies/Halloween Pumpkin Chariot Minion A.png',
    './img/sv_enemies/Halloween Pumpkin Chariot Minion B.png',
    './img/sv_enemies/Halloween Pumpkin Chariot No Minion.png',
    './img/sv_enemies/Halloween Pumpkin Chariot.png',
    './img/sv_enemies/Halloween Pumpkin Gentleman.png',
    './img/sv_enemies/Halloween Pumpkin.png',
    './img/sv_enemies/Halloween Skeleton.png',
    './img/sv_enemies/Halloween Spirit Mumpkin.png',
    './img/sv_enemies/Halloween Stein Monster.png',
    './img/sv_enemies/Halloween Stein\'s Monster MK2.png',
    './img/sv_enemies/Halloween Vampire.png',
    './img/sv_enemies/Halloween Witch Baba.png',
    './img/sv_enemies/Halloween Witch.png',
    './img/sv_enemies/Harpy.png',
    './img/sv_enemies/Highking.png',
    './img/sv_enemies/Hi_monster.png',
    './img/sv_enemies/Hydra.png',
    './img/sv_enemies/Ice Avian.png',
    './img/sv_enemies/Ice Bull.png',
    './img/sv_enemies/Ice Cave Bat.png',
    './img/sv_enemies/Ice Glacier SPawn.png',
    './img/sv_enemies/Ice Golem.png',
    './img/sv_enemies/Ice Kindred Glacier.png',
    './img/sv_enemies/Ice Lion.png',
    './img/sv_enemies/Ice Ogre.png',
    './img/sv_enemies/Ice Snake.png',
    './img/sv_enemies/Ice Snobros.png',
    './img/sv_enemies/Ice Snowball.png',
    './img/sv_enemies/Ice Snowman.png',
    './img/sv_enemies/Ice Spike.png',
    './img/sv_enemies/Ice Turtle.png',
    './img/sv_enemies/Ice Whisp.png',
    './img/sv_enemies/Ice Yeti Whisp.png',
    './img/sv_enemies/Ice Yeti.png',
    './img/sv_enemies/Insect Red Ant Knight.png',
    './img/sv_enemies/Insects Ant Lion.png',
    './img/sv_enemies/Insects Bee.png',

    './img/sv_enemies/Insects Black Ant Archer.png',
    './img/sv_enemies/Insects Black Ant Berserker.png',
    './img/sv_enemies/Insects Black Ant Knight.png',
    './img/sv_enemies/Insects Black Ant Mage.png',
    './img/sv_enemies/Insects Black Ant Protector.png',
    './img/sv_enemies/Insects Caterpillar A.png',
    './img/sv_enemies/Insects Caterpillar B.png',
    './img/sv_enemies/Insects Dragon.png',
    './img/sv_enemies/Insects Dragonfly B.png',
    './img/sv_enemies/Insects Dragonfly.png',
    './img/sv_enemies/Insects eyehopper.png',
    './img/sv_enemies/Insects Fire Ant.png',
    './img/sv_enemies/Insects Giant Bug Centipede.png',
    './img/sv_enemies/Insects Giant Bug Death Worm A.png',
    './img/sv_enemies/Insects Giant Bug Death Worm B.png',
    './img/sv_enemies/Insects Giant Bug Hercules.png',
    './img/sv_enemies/Insects Hell Mantis.png',
    './img/sv_enemies/Insects Lunar Butterfly.png',
    './img/sv_enemies/Insects Roach.png',
    './img/sv_enemies/Insects Scarab.png',
    './img/sv_enemies/Insects Sickle Mantis.png',
    './img/sv_enemies/Insects Swarm.png',
    './img/sv_enemies/Insects Tick.png',
    './img/sv_enemies/Insects Tridentpupa.png',
    './img/sv_enemies/Insects Waterstrider.png',
    './img/sv_enemies/Ketos.png',
    './img/sv_enemies/Knight Axe Common.png',
    './img/sv_enemies/Knight Axe Elite.png',
    './img/sv_enemies/Knight Blunderbuss Common.png',
    './img/sv_enemies/Knight Blunderbuss Elite.png',
    './img/sv_enemies/Knight Spear Elite.png',
    './img/sv_enemies/Knight Sword Elite.png',
    './img/sv_enemies/Knights Spear Common.png',
    './img/sv_enemies/Knights Sword Common.png',
    './img/sv_enemies/Kobolds Dagger Kobold.png',
    './img/sv_enemies/Kobolds Mage Kobold.png',
    './img/sv_enemies/Kobolds Spear Kobold.png',
    './img/sv_enemies/Kraken.png',
    './img/sv_enemies/Lamia.png',
    './img/sv_enemies/Legendary Knight Ansellus.png',
    './img/sv_enemies/Legendary Knight Arriete.png',
    './img/sv_enemies/Legendary Knight Arriette F.png',
    './img/sv_enemies/Legendary Knight Croix.png',
    './img/sv_enemies/Legendary Knight Dalton.png',
    './img/sv_enemies/Legendary Knight Dante.png',
    './img/sv_enemies/Legendary Knight Jeanne.png',
    './img/sv_enemies/Legendary Knight King Archial.png',
    './img/sv_enemies/Legendary Knight Michael.png',
    './img/sv_enemies/Legendary Knight Pizarro B.png',
    './img/sv_enemies/Legendary Knight Pizarro.png',
    './img/sv_enemies/Legendary Knight Regulus.png',
    './img/sv_enemies/Legendary Knight Remment.png',
    './img/sv_enemies/Legendary Knight Sen.png',
    './img/sv_enemies/Legendary Knight Serat.png',
    './img/sv_enemies/Legendary Knight Zidh B.png',
    './img/sv_enemies/Legendary Knight Zidh.png',
    './img/sv_enemies/Legendary Knights Blacksmith Remment.png',
    './img/sv_enemies/Legendary Knights Dancer Zidh.png',
    './img/sv_enemies/Legendary Knights Disciple Chain.png',
    './img/sv_enemies/Legendary Knights Disciple Moonblade.png',
    './img/sv_enemies/Legendary Knights Disciple Pike.png',
    './img/sv_enemies/Legendary Knights Huntress Arriette.png',
    './img/sv_enemies/Legendary Knights Minion Axe.png',
    './img/sv_enemies/Legendary Knights Minion Claymore.png',
    './img/sv_enemies/Legendary Knights Minion Spear.png',
    './img/sv_enemies/Legendary Knights Nobleman Ansellus.png',
    './img/sv_enemies/Legendary Knights Scholar Jeanne.png',
    './img/sv_enemies/Legendary Knights Summoner Dante A.png',
    './img/sv_enemies/Legendary Knights Summoner Dante B.png',
    './img/sv_enemies/Library Book Golem.png',
    './img/sv_enemies/Library Book Master.png',
    './img/sv_enemies/Library Book Swarm B.png',
    './img/sv_enemies/Library Book Swarm.png',
    './img/sv_enemies/Lich.png',
    './img/sv_enemies/Light Angel Heavy Knight.png',
    './img/sv_enemies/Light Angel Knight.png',
    './img/sv_enemies/Light Angel Maiden.png',
    './img/sv_enemies/Light Creatures Throne.png',
    './img/sv_enemies/Light Dragon.png',
    './img/sv_enemies/Light Gemstone A.png',
    './img/sv_enemies/Light Gemstone B.png',
    './img/sv_enemies/Light Gemstone C.png',

    './img/sv_enemies/Light Holy Orb.png',
    './img/sv_enemies/Light Scholar Angel.png',
    './img/sv_enemies/Light Slime.png',
    './img/sv_enemies/Light Snake.png',
    './img/sv_enemies/Light Summoned Angel.png',
    './img/sv_enemies/Light Wisp.png',
    './img/sv_enemies/Light Wolf.png',
    './img/sv_enemies/Machinerybee.png',
    './img/sv_enemies/Machines Airship.png',
    './img/sv_enemies/Machines Cannon.png',
    './img/sv_enemies/Machines Fantasy Tank A.png',
    './img/sv_enemies/Machines Fantasy Tank B.png',
    './img/sv_enemies/MAchines Fantasy Tank C.png',
    './img/sv_enemies/Machines Fantasy Tank D.png',
    './img/sv_enemies/Machines Zeppellin.png',
    './img/sv_enemies/Mage Garrintan.png',
    './img/sv_enemies/Matango.png',
    './img/sv_enemies/Mechascorpion.png',
    './img/sv_enemies/Medieval Bandit Child.png',
    './img/sv_enemies/Medieval Bandit Dagger Gun.png',
    './img/sv_enemies/Medieval Bandit Great Sword.png',
    './img/sv_enemies/Medusa.png',
    './img/sv_enemies/Megapack II Avian A.png',
    './img/sv_enemies/Megapack II Avian Elephant.png',
    './img/sv_enemies/Megapack II Betafish.png',
    './img/sv_enemies/Megapack II Biofish.png',
    './img/sv_enemies/Megapack II Black Lance Knight.png',
    './img/sv_enemies/Megapack II Blue Seeker.png',
    './img/sv_enemies/Megapack II Bug Originator.png',
    './img/sv_enemies/Megapack II Colossal Mummy.png',
    './img/sv_enemies/Megapack II Crocoknight.png',
    './img/sv_enemies/Megapack II Diamond Dog.png',
    './img/sv_enemies/Megapack II Dryad Mini.png',
    './img/sv_enemies/Megapack II Electroctopus.png',
    './img/sv_enemies/Megapack II Feathered Snake.png',
    './img/sv_enemies/Megapack II Flame Monkey.png',
    './img/sv_enemies/Megapack II Forest Six-Wing Fairy.png',
    './img/sv_enemies/Megapack II Frost Gorilla.png',
    './img/sv_enemies/Megapack II Horn Willow.png',
    './img/sv_enemies/MEgapack II Hornet Warrior.png',
    './img/sv_enemies/Megapack II Mountain Razortail Eagle.png',
    './img/sv_enemies/Megapack II Red Shroom A.png',
    './img/sv_enemies/MEgapack II Red Shroom B.png',
    './img/sv_enemies/Megapack II Roaming Salamander.png',
    './img/sv_enemies/Megapack II Rocktail Demolisher.png',
    './img/sv_enemies/Megapack II Samurai Skeleton.png',
    './img/sv_enemies/Megapack II Shadow Knight.png',
    './img/sv_enemies/Megapack II Silver Avian.png',
    './img/sv_enemies/Megapack II Spike Hopper.png',
    './img/sv_enemies/Megapack II Spiked Caterpillar.png',
    './img/sv_enemies/Megapack II Toucan Panther.png',
    './img/sv_enemies/Megapack II Void Demon B.png',
    './img/sv_enemies/Megapack II White Minotaur.png',
    './img/sv_enemies/Megapack II Wingless Dragon.png',
    './img/sv_enemies/Megapack III Axe Warrior Dwarf.png',
    './img/sv_enemies/Megapack III Behemoth.png',
    './img/sv_enemies/Megapack III Black Iron Minotaur Beef.png',
    './img/sv_enemies/Megapack III Cerberus Ptolemaios.png',
    './img/sv_enemies/Megapack III Dragonslayer Dwarf.png',
    './img/sv_enemies/Megapack III Elemental Lords Fire Lord.png',
    './img/sv_enemies/Megapack III Elemental Lords Ice Maiden.png',
    './img/sv_enemies/Megapack III Fallen Kings Arcane King Jeffroy.png',
    './img/sv_enemies/Megapack III Fallen Kings King Of Dwarves Skor.png',
    './img/sv_enemies/Megapack III Fallen Kings King Of Elves Dreyel.png',
    './img/sv_enemies/Megapack III Fallen Kings King Of Giants Goken.png',
    './img/sv_enemies/Megapack III Hellhound Inferni.png',
    './img/sv_enemies/Megapack III Red Guard A.png',
    './img/sv_enemies/Megapack III Red Guard B.png',
    './img/sv_enemies/Megapack III Red Guard C.png',
    './img/sv_enemies/Megapack III Undead Warrior Benkei.png',
    './img/sv_enemies/Megapack III Void Gargoyle.png',
    './img/sv_enemies/Megapack III Zodiac Aries.png',
    './img/sv_enemies/Megpack III Drill Dwarf.png',
    './img/sv_enemies/Megpack III Fallen Kings Undead King Berthelot.png',
    './img/sv_enemies/Mercenary.png',
    './img/sv_enemies/Mimic Armor.png',
    './img/sv_enemies/Mimic Barrel.png',
    './img/sv_enemies/Mimic Book.png',
    './img/sv_enemies/Mimic Bow.png',
    './img/sv_enemies/Mimic Bush.png',

    './img/sv_enemies/Mimic Chest.png',
    './img/sv_enemies/Mimic Cloak.png',
    './img/sv_enemies/Mimic Crystal.png',
    './img/sv_enemies/Mimic Door.png',
    './img/sv_enemies/Mimic Humanoid.png',
    './img/sv_enemies/Mimic Jar.png',
    './img/sv_enemies/Mimic Paper Plane.png',
    './img/sv_enemies/Mimic Potion.png',
    './img/sv_enemies/Mimic Sarcophagus.png',
    './img/sv_enemies/Mimic Shield.png',
    './img/sv_enemies/Mimic Slime.png',
    './img/sv_enemies/Mimic Sword.png',
    './img/sv_enemies/Mimic.png',
    './img/sv_enemies/Minotaur Beef.png',
    './img/sv_enemies/Minotaur BloodshotBeef.png',
    './img/sv_enemies/Mirror Mimic.png',
    './img/sv_enemies/Mountain Bat.png',
    './img/sv_enemies/Mountain Black Wolf.png',
    './img/sv_enemies/Mountain Bull Dragon.png',
    './img/sv_enemies/Mountain Bunny.png',
    './img/sv_enemies/Mountain Chimera.png',
    './img/sv_enemies/Mountain Dodo.png',
    './img/sv_enemies/Mountain Fetero.png',
    './img/sv_enemies/Mountain Goat.png',
    './img/sv_enemies/Mountain Greathorn Goat.png',
    './img/sv_enemies/Mountain Griffon.png',
    './img/sv_enemies/Mountain Harpy.png',
    './img/sv_enemies/Mountain Hornette.png',
    './img/sv_enemies/Mountain Nanjo.png',
    './img/sv_enemies/Mountain Owl.png',
    './img/sv_enemies/Mountain Peacock.png',
    './img/sv_enemies/Mountain Rock Mimic.png',
    './img/sv_enemies/Mountain Scorpion Scopus.png',
    './img/sv_enemies/Mountain Serpens.png',
    './img/sv_enemies/Mountain Snail.png',
    './img/sv_enemies/Mountain Warthog.png',
    './img/sv_enemies/Mountain Werebear Martz.png',
    './img/sv_enemies/Mountain Winter Wolf.png',
    './img/sv_enemies/Mountain Wolf.png',
    './img/sv_enemies/MountainScarbear.png',
    './img/sv_enemies/Moutain Behemoth.png',
    './img/sv_enemies/Mushroom Don.png',
    './img/sv_enemies/Mushroom Shroomslinger.png',
    './img/sv_enemies/Objects Ace Club.png',
    './img/sv_enemies/Objects Ace Diamond.png',
    './img/sv_enemies/Objects Ace Heart.png',
    './img/sv_enemies/Objects Ace Spade.png',
    './img/sv_enemies/Objects Assault Station.png',
    './img/sv_enemies/Objects bBishop.png',
    './img/sv_enemies/Objects bHorse.png',
    './img/sv_enemies/Objects bKing.png',
    './img/sv_enemies/Objects bPawnA.png',
    './img/sv_enemies/Objects bPawnB.png',
    './img/sv_enemies/Objects bQueen.png',
    './img/sv_enemies/Objects bTower.png',
    './img/sv_enemies/Objects Dorian.png',
    './img/sv_enemies/Objects Driller.png',
    './img/sv_enemies/Objects Madpill.png',
    './img/sv_enemies/Objects Madsule.png',
    './img/sv_enemies/Objects Mainframe.png',
    './img/sv_enemies/Objects Medibros.png',
    './img/sv_enemies/Objects Twin handheld.png',
    './img/sv_enemies/Objects wBishop.png',
    './img/sv_enemies/Objects wHorse.png',
    './img/sv_enemies/Objects wKing.png',
    './img/sv_enemies/Objects wPawnA.png',
    './img/sv_enemies/Objects wPawnB.png',
    './img/sv_enemies/Objects wQueen.png',
    './img/sv_enemies/Objects wTower.png',
    './img/sv_enemies/Objects YBox.png',
    './img/sv_enemies/Oddegg.png',
    './img/sv_enemies/Orc Archer Weak.png',
    './img/sv_enemies/Orc Archer.png',
    './img/sv_enemies/Orc Axe Warrior Weak.png',
    './img/sv_enemies/Orc Axe Warrior.png',
    './img/sv_enemies/Orc Axe Warrior_W.png',
    './img/sv_enemies/Orc Sword Warrior Weak.png',
    './img/sv_enemies/Orc Sword Warrior.png',
    './img/sv_enemies/Orc War Drummer Weak.png',
    './img/sv_enemies/Orc War Drummer.png',
    './img/sv_enemies/Orc Warlock Weak.png',
    './img/sv_enemies/Orc Warlock.png',
    './img/sv_enemies/Petitdevil.png',

    './img/sv_enemies/Pirate Bandit.png',
    './img/sv_enemies/Pirate Captain.png',
    './img/sv_enemies/Pirate Magic Scimitar.png',
    './img/sv_enemies/Pirate Monkey.png',
    './img/sv_enemies/Pirate Parrot.png',
    './img/sv_enemies/Pirate Skeleton.png',
    './img/sv_enemies/Plant Warriors Cape Sundew.png',
    './img/sv_enemies/Plant Warriors Rose Knight.png',
    './img/sv_enemies/Plant Warriors Screamer Mandrake.png',
    './img/sv_enemies/Plasma.png',
    './img/sv_enemies/Possessed Knights Axe.png',
    './img/sv_enemies/Possessed Knights Gun.png',
    './img/sv_enemies/Possessed Knights Saber.png',
    './img/sv_enemies/Post-Modern Machinery Assault.png',
    './img/sv_enemies/Post-Modern Machinery Heavy.png',
    './img/sv_enemies/Post-Modern Machinery Scout.png',
    './img/sv_enemies/Post-Modern Soldier A.png',
    './img/sv_enemies/Post-Modern Soldier B.png',
    './img/sv_enemies/Post-Modern Soldier C.png',
    './img/sv_enemies/Pre-Legendary Knights Cursed Swordsman Michael.png',
    './img/sv_enemies/Pre-legendary Knights Inventor Sen.png',
    './img/sv_enemies/Pre-Legendary Knights Onna-bugeisha Croix.png',
    './img/sv_enemies/Rabbit Warriors Archer.png',
    './img/sv_enemies/Rabbit Warriors Bandit.png',
    './img/sv_enemies/Rabbit Warriors Knight.png',
    './img/sv_enemies/Robot Dracozord.png',
    './img/sv_enemies/Rock golem.png',
    './img/sv_enemies/Rogue Bastard Sword.png',
    './img/sv_enemies/Rogue Dagger Monk.png',
    './img/sv_enemies/Rogue Twin Dagger.png',
    './img/sv_enemies/Sailor.png',
    './img/sv_enemies/Salamander.png',
    './img/sv_enemies/Sandworm.png',
    './img/sv_enemies/Sea Abismos.png',
    './img/sv_enemies/Sea Arman.png',
    './img/sv_enemies/Sea Armes.png',
    './img/sv_enemies/Sea Armon.png',
    './img/sv_enemies/Sea Beach Dark Shell.png',
    './img/sv_enemies/Sea Beach Dark Star.png',
    './img/sv_enemies/Sea Beach Emperor Crab A.png',
    './img/sv_enemies/Sea Beach Emperor Crab B.png',
    './img/sv_enemies/Sea Beach Hermit Crab.png',
    './img/sv_enemies/Sea Beach Pelican.png',
    './img/sv_enemies/Sea Beach Seagull.png',
    './img/sv_enemies/Sea Beach Shell Claw A.png',
    './img/sv_enemies/Sea Beach Shell Claw B.png',
    './img/sv_enemies/Sea Beach Spider Crab A.png',
    './img/sv_enemies/Sea Beach Spider Crab B.png',
    './img/sv_enemies/Sea Beach Spikestar .png',
    './img/sv_enemies/Sea Beach Spore.png',
    './img/sv_enemies/Sea Beach Star Shell.png',
    './img/sv_enemies/Sea Beach Stars.png',
    './img/sv_enemies/Sea Beach Turtle Golem.png',
    './img/sv_enemies/Sea Beach Turtle.png',
    './img/sv_enemies/Sea Beach Urchin.png',
    './img/sv_enemies/Sea Beach War Lobster A.png',
    './img/sv_enemies/Sea Beach War Lobster B.png',
    './img/sv_enemies/Sea Blue Dragon.png',
    './img/sv_enemies/Sea Crab.png',
    './img/sv_enemies/Sea Fatoad.png',
    './img/sv_enemies/Sea Fish A.png',
    './img/sv_enemies/Sea Fish B.png',
    './img/sv_enemies/Sea Fish C.png',
    './img/sv_enemies/Sea Horntle.png',
    './img/sv_enemies/Sea Horse.png',
    './img/sv_enemies/Sea Jellyfish.png',
    './img/sv_enemies/Sea Lickitoad.png',
    './img/sv_enemies/Sea Lurker.png',
    './img/sv_enemies/Sea Mermaid Warrior Arliette.png',
    './img/sv_enemies/Sea Mermaid Warrior Sasha.png',
    './img/sv_enemies/Sea Mermaid Warrior Sion.png',
    './img/sv_enemies/Sea Mermaid.png',
    './img/sv_enemies/Sea Octi.png',
    './img/sv_enemies/Sea Octopus.png',
    './img/sv_enemies/Sea Piranos.png',
    './img/sv_enemies/Sea Seaweed Cannon.png',
    './img/sv_enemies/Sea Shark.png',
    './img/sv_enemies/Sea Shelltacke.png',
    './img/sv_enemies/Sea Spheria.png',
    './img/sv_enemies/Sea Tortoad.png',

    './img/sv_enemies/Sea Turtle.png',
    './img/sv_enemies/Sea Vamphibian.png',
    './img/sv_enemies/Secondary Elementals Acid Elemental.png',
    './img/sv_enemies/Secondary Elementals Time Elemental.png',
    './img/sv_enemies/Secondary Elementals War Elemental.png',
    './img/sv_enemies/Seven Sins Gluttony.png',
    './img/sv_enemies/Seven Sins Greed.png',
    './img/sv_enemies/Seven Sins Lust.png',
    './img/sv_enemies/Seven Sins Pride.png',
    './img/sv_enemies/Seven Sins Sloth.png',
    './img/sv_enemies/Seven Sins Wrath.png',
    './img/sv_enemies/SF_Agent.png',
    './img/sv_enemies/SF_Anaconda.png',
    './img/sv_enemies/SF_ArmyGorilla.png',
    './img/sv_enemies/SF_Armymonkey.png',
    './img/sv_enemies/SF_Blueogre.png',
    './img/sv_enemies/SF_Boss.png',
    './img/sv_enemies/SF_Brownbear.png',
    './img/sv_enemies/SF_Cyborg.png',
    './img/sv_enemies/SF_Demon_of_universe.png',
    './img/sv_enemies/SF_Drone.png',
    './img/sv_enemies/SF_Enmadaio.png',
    './img/sv_enemies/SF_Evilteddybear.png',
    './img/sv_enemies/SF_Hannyamask.png',
    './img/sv_enemies/SF_Hermit.png',
    './img/sv_enemies/SF_Jiangshi.png',
    './img/sv_enemies/SF_Kamaitachi.png',
    './img/sv_enemies/SF_Kappa.png',
    './img/sv_enemies/SF_Madclown.png',
    './img/sv_enemies/SF_Madscientist.png',
    './img/sv_enemies/SF_Mafia.png',
    './img/sv_enemies/SF_Mechasphere.png',
    './img/sv_enemies/SF_Phoenix.png',
    './img/sv_enemies/SF_Redogre.png',
    './img/sv_enemies/SF_Securityrobot.png',
    './img/sv_enemies/SF_Shadow.png',
    './img/sv_enemies/SF_Skullmask.png',
    './img/sv_enemies/SF_Slaughterrobot.png',
    './img/sv_enemies/SF_Specialforces.png',
    './img/sv_enemies/SF_Talkingmuppet.png',
    './img/sv_enemies/SF_Timebomb.png',
    './img/sv_enemies/SF_Whitewolf.png',
    './img/sv_enemies/SF_Will_o_the_wisp.png',
    './img/sv_enemies/SF_Wolf.png',
    './img/sv_enemies/SF_Workrobot.png',
    './img/sv_enemies/SF_Zombiedog.png',
    './img/sv_enemies/Siren.png',
    './img/sv_enemies/Skeleton Archer Sisbon.png',
    './img/sv_enemies/Skeleton Archer.png',
    './img/sv_enemies/Skeleton Dragon.png',
    './img/sv_enemies/Skeleton Hare.png',
    './img/sv_enemies/Skeleton Knight Alstreim.png',
    './img/sv_enemies/Skeleton Knight Baron.png',
    './img/sv_enemies/Skeleton Knight Debon.png',
    './img/sv_enemies/Skeleton Knight Debons.png',
    './img/sv_enemies/Skeleton Mage Mabon.png',
    './img/sv_enemies/Skeleton Mage.png',
    './img/sv_enemies/Skull Knight Xoer.png',
    './img/sv_enemies/Slime Blue.png',
    './img/sv_enemies/Slime Darki.png',
    './img/sv_enemies/Slime Darkii.png',
    './img/sv_enemies/Slime Darkiii.png',
    './img/sv_enemies/Slime Earthi.png',
    './img/sv_enemies/Slime Earthii.png',
    './img/sv_enemies/Slime Earthiii.png',
    './img/sv_enemies/Slime Firei.png',
    './img/sv_enemies/Slime Fireii.png',
    './img/sv_enemies/Slime Fireiii.png',
    './img/sv_enemies/Slime Holyi.png',
    './img/sv_enemies/Slime Holyii.png',
    './img/sv_enemies/Slime Holyiii.png',
    './img/sv_enemies/Slime Icei.png',
    './img/sv_enemies/Slime Iceii.png',
    './img/sv_enemies/Slime Iceiii.png',
    './img/sv_enemies/Slime RPG Attacker.png',
    './img/sv_enemies/Slime RPG Basic.png',
    './img/sv_enemies/Slime RPG Buffer.png',
    './img/sv_enemies/Slime RPG Caster.png',
    './img/sv_enemies/Slime RPG Debuffer.png',
    './img/sv_enemies/Slime RPG Defender.png',
    './img/sv_enemies/Slime RPG Healer.png',
    './img/sv_enemies/Slime RPG King.png',
    './img/sv_enemies/Slime Thunderi.png',
    './img/sv_enemies/Slime Thunderii.png',
    './img/sv_enemies/Slime Thunderiii.png',
    './img/sv_enemies/Slime Wateri.png',

    './img/sv_enemies/Slime Waterii.png',
    './img/sv_enemies/Slime Wateriii.png',
    './img/sv_enemies/Slime Windi.png',
    './img/sv_enemies/Slime Windii.png',
    './img/sv_enemies/Slime Windiii.png',
    './img/sv_enemies/Slimei.png',
    './img/sv_enemies/Slimeii.png',
    './img/sv_enemies/slimeiii.png',
    './img/sv_enemies/Sorcerer.png',
    './img/sv_enemies/Special Spiders Dragon Spider.png',
    './img/sv_enemies/Special Spiders Fire Spider.png',
    './img/sv_enemies/Special Spiders Ghost Spider.png',
    './img/sv_enemies/Stoneknight.png',
    './img/sv_enemies/Summon Alicorn.png',
    './img/sv_enemies/Summon Carbuncle.png',
    './img/sv_enemies/Summon Ifrit.png',
    './img/sv_enemies/Summon Odin.png',
    './img/sv_enemies/Summon Shiva.png',
    './img/sv_enemies/Sylph.png',
    './img/sv_enemies/Tigerbunny.png',
    './img/sv_enemies/Titan Alfadriel.png',
    './img/sv_enemies/Titan Aquos.png',
    './img/sv_enemies/Titan Darkness Ilnoct.png',
    './img/sv_enemies/Titan Earth Terran.png',
    './img/sv_enemies/Titan Fire Ignis.png',
    './img/sv_enemies/Titan Ice Demeres.png',
    './img/sv_enemies/Titan Wind Ventoss.png',
    './img/sv_enemies/Titans Thunder Dynamo.png',
    './img/sv_enemies/Toxic Cactus A.png',
    './img/sv_enemies/Toxic Cactus B.png',
    './img/sv_enemies/Toxic Cactus C.png',
    './img/sv_enemies/Toxic Carnivorous Plant A.png',
    './img/sv_enemies/Toxic Carnivorous Plant B.png',
    './img/sv_enemies/Toxic Carnivorous Plant C.png',
    './img/sv_enemies/Toxic Frog A.png',
    './img/sv_enemies/Toxic FRog A2.png',
    './img/sv_enemies/Toxic Frog B.png',
    './img/sv_enemies/Toxic Frog B2.png',
    './img/sv_enemies/Toxic Frog C.png',
    './img/sv_enemies/Toxic Frog C2.png',
    './img/sv_enemies/Toxic Maneater Plan A.png',
    './img/sv_enemies/Toxic Maneater Plant B.png',
    './img/sv_enemies/Toxic Maneater Plant C.png',
    './img/sv_enemies/Toxic Root A.png',
    './img/sv_enemies/Toxic Root B.png',
    './img/sv_enemies/Toxic Shroom A.png',
    './img/sv_enemies/Toxic Shroom B.png',
    './img/sv_enemies/Toxic Shroom C.png',
    './img/sv_enemies/Treant.png',
    './img/sv_enemies/Tribal Elves Bastard Sword.png',
    './img/sv_enemies/Tribal Elves Dagger.png',
    './img/sv_enemies/Tribal Elves Rapier.png',
    './img/sv_enemies/Undead Benkei.png',
    './img/sv_enemies/Undead Claw Knight.png',
    './img/sv_enemies/Undead Gigaraven.png',
    './img/sv_enemies/Undead Jiangshi.png',
    './img/sv_enemies/Undead Skull Slime.png',
    './img/sv_enemies/Undead Skull Tree.png',
    './img/sv_enemies/Undead Slime.png',
    './img/sv_enemies/Undead Walker.png',
    './img/sv_enemies/Undead Wolf.png',
    './img/sv_enemies/Undine.png',
    './img/sv_enemies/Unicorn.png',
    './img/sv_enemies/Vampiric Creature Dragon Lamprey.png',
    './img/sv_enemies/Vampiric Creatures Flying Leech.png',
    './img/sv_enemies/Vampiric Creatures Giant Mosquito.png',
    './img/sv_enemies/Voidoll Erabos.png',
    './img/sv_enemies/Voidoll Erebia.png',
    './img/sv_enemies/Voidoll Erebus.png',
    './img/sv_enemies/Weretiger Maxima.png',
    './img/sv_enemies/Werewolf Rigel.png',
    './img/sv_enemies/Whisp Wispia.png',
    './img/sv_enemies/Wind Avian.png',
    './img/sv_enemies/Wind Bunny.png',
    './img/sv_enemies/Wind Fairy.png',
    './img/sv_enemies/Wind Feathered Golem.png',
    './img/sv_enemies/Wind Feathered Razor.png',
    './img/sv_enemies/Wind Harpy.png',
    './img/sv_enemies/Wind Lion.png',
    './img/sv_enemies/Wind Mantis.png',
    './img/sv_enemies/Wind Snake.png',
    './img/sv_enemies/Wind Spawn.png',
    './img/sv_enemies/Wind Wisp.png',
    './img/sv_enemies/Witch Hunters Healer.png',
    './img/sv_enemies/Witch Hunters Leader.png',
    './img/sv_enemies/Witch Hunters Noble.png',
    './img/sv_enemies/Witch.png',
    './img/sv_enemies/Wolfman.png',
    './img/sv_enemies/Wraith.png',
    './img/sv_enemies/Xmas Bear.png',
    './img/sv_enemies/Xmas Cookie.png',
    './img/sv_enemies/Xmas Penguin.png',
    './img/sv_enemies/Xmas Snowman.png',
    './img/sv_enemies/Xmas Tree.png',
    './img/sv_enemies/Zodiac Aquarius B.png',
    './img/sv_enemies/Zodiac Aquarius.png',
    './img/sv_enemies/Zodiac Aries B.png',
    './img/sv_enemies/Zodiac Aries.png',
    './img/sv_enemies/Zodiac Capricorn.png',
    './img/sv_enemies/Zodiac Creatures Cancer.png',
    './img/sv_enemies/Zodiac Creatures Libra.png',
    './img/sv_enemies/Zodiac Creatures Ophichus.png',
    './img/sv_enemies/Zodiac Creatures Pisces.png',

    './img/sv_enemies/Zodiac Creatures Saggitarius.png',
    './img/sv_enemies/Zodiac Creatures Scorpion.png',
    './img/sv_enemies/Zodiac Gemini.png',
    './img/sv_enemies/Zodiac Leo B.png',
    './img/sv_enemies/Zodiac Leo.png',
    './img/sv_enemies/Zodiac Taurus.png',
    './img/sv_enemies/Zodiac Virgo B.png',
    './img/sv_enemies/Zodiac Virgo.png',
    './img/sv_enemies/Zombie.png',

    './img/system/Balloon.png',
    './img/system/ButtonSet.png',
    './img/system/GameOver.png',
    './img/system/IconSet.png',
    './img/system/Shadow1.png',
    './img/system/Shadow2.png',
    './img/system/Splash.png',
    './img/system/States.png',
    './img/system/Weapons1.png',
    './img/system/Weapons2.png',
    './img/system/Weapons3.png',
    './img/system/Window.png',

    './img/tilesets/2b8Dz7o.png',
    './img/tilesets/73nunEG.png',
    './img/tilesets/aEEGgAW.png',
    './img/tilesets/all_castles.png',
    './img/tilesets/beach.png',
    './img/tilesets/beach_env.png',
    './img/tilesets/beach_sand.png',
    './img/tilesets/church2.png',
    './img/tilesets/church_light.png',
    './img/tilesets/Demon.png',
    './img/tilesets/deserttiles2.png',
    './img/tilesets/deser_a2.png',
    './img/tilesets/Dungeon_A1.png',
    './img/tilesets/Dungeon_A1.txt',
    './img/tilesets/Dungeon_A2.png',
    './img/tilesets/Dungeon_A2.txt',
    './img/tilesets/Dungeon_A4.png',
    './img/tilesets/Dungeon_A4.txt',
    './img/tilesets/Dungeon_A5.png',
    './img/tilesets/Dungeon_A5.txt',
    './img/tilesets/Dungeon_B.png',
    './img/tilesets/Dungeon_B.txt',
    './img/tilesets/Dungeon_C.png',
    './img/tilesets/Dungeon_C.txt',
    './img/tilesets/EmMTubq.png',
    './img/tilesets/floor_church.png',
    './img/tilesets/floor_library.png',
    './img/tilesets/gDwN2Qm.png',
    './img/tilesets/hsHR7wn.png',
    './img/tilesets/Inside_A1.png',
    './img/tilesets/Inside_A1.txt',
    './img/tilesets/Inside_A2.png',
    './img/tilesets/Inside_A2.txt',
    './img/tilesets/Inside_A4.png',
    './img/tilesets/Inside_A4.txt',
    './img/tilesets/Inside_A5.png',
    './img/tilesets/Inside_A5.txt',
    './img/tilesets/Inside_B.png',
    './img/tilesets/Inside_B.txt',
    './img/tilesets/Inside_C.png',
    './img/tilesets/Inside_C.txt',
    './img/tilesets/Ix06wOp.png',
    './img/tilesets/jjn7lnP.png',
    './img/tilesets/JwiIVd2.png',
    './img/tilesets/library_books.png',
    './img/tilesets/M8UJgav.png',
    './img/tilesets/Magma Tilesets.png',
    './img/tilesets/Magma Walls.png',
    './img/tilesets/mansion_roofs.png',
    './img/tilesets/mansion_tile.png',
    './img/tilesets/NGdIwWC.png',
    './img/tilesets/nJA5We9.png',
    './img/tilesets/Outside_A1.png',
    './img/tilesets/Outside_A1.txt',
    './img/tilesets/Outside_A2.png',
    './img/tilesets/Outside_A2.txt',
    './img/tilesets/Outside_A3.png',
    './img/tilesets/Outside_A3.txt',
    './img/tilesets/Outside_A4.png',
    './img/tilesets/Outside_A4.txt',
    './img/tilesets/Outside_A5.png',
    './img/tilesets/Outside_A5.txt',
    './img/tilesets/Outside_B.png',
    './img/tilesets/Outside_B.txt',
    './img/tilesets/Outside_C.png',
    './img/tilesets/Outside_C.txt',
    './img/tilesets/paintings.png',
    './img/tilesets/qtA0Rwy.png',
    './img/tilesets/relictile.png',
    './img/tilesets/ruinwall.png',
    './img/tilesets/sekaiju.png',
    './img/tilesets/sekaiju0.png',
    './img/tilesets/sekaiju1.png',
    './img/tilesets/sekaiju2.png',
    './img/tilesets/sekaiju4.png',
    './img/tilesets/sekaiu2.png',
    './img/tilesets/SF_Inside_443.png',
    './img/tilesets/SF_Inside_A4.png',
    './img/tilesets/SF_Inside_A4.txt',
    './img/tilesets/SF_Inside_B.png',
    './img/tilesets/SF_Inside_B.txt',
    './img/tilesets/SF_Inside_C.png',
    './img/tilesets/SF_Inside_C.txt',
    './img/tilesets/SF_Outside_A3.png',
    './img/tilesets/SF_Outside_A3.txt',
    './img/tilesets/SF_Outside_A4.png',
    './img/tilesets/SF_Outside_A4.txt',
    './img/tilesets/SF_Outside_A5.png',
    './img/tilesets/SF_Outside_A5.txt',
    './img/tilesets/SF_Outside_B.png',
    './img/tilesets/SF_Outside_B.txt',
    './img/tilesets/SF_Outside_C.png',
    './img/tilesets/SF_Outside_C.txt',
    './img/tilesets/Terms.txt',
    './img/tilesets/tileset.png',
    './img/tilesets/U87V3bI.png',
    './img/tilesets/v2XONpt.png',
    './img/tilesets/wall_church.png',
    './img/tilesets/wall_library.png',
    './img/tilesets/wall_mansion.png',
    './img/tilesets/WCoFryR.png',
    './img/tilesets/World_A1.png',
    './img/tilesets/World_A1.txt',
    './img/tilesets/World_A2.png',
    './img/tilesets/World_A2.txt',
    './img/tilesets/World_B.png',
    './img/tilesets/World_B.txt',
    './img/tilesets/World_C.png',
    './img/tilesets/World_C.txt',

    './img/titles1/Beach.png',
    './img/titles1/Bigtree.png',
    './img/titles1/Canyon.png',
    './img/titles1/FlyingIsland.png',
    './img/titles1/Gate.png',
    './img/titles1/Gold.png',
    './img/titles1/Jungle.png',
    './img/titles1/Mansion.png',
    './img/titles1/Monument.png',
    './img/titles1/Mountain.png',
    './img/titles1/Night.png',
    './img/titles1/Oasis.png',
    './img/titles1/Ruins.png',
    './img/titles1/Sky.png',
    './img/titles1/Snow.png',
    './img/titles1/Sword.png',
    './img/titles1/Town1.png',
    './img/titles1/Town2.png',
    './img/titles1/Universe.png',
    './img/titles1/Wasteland.png',
    './img/titles2/Floral.png',
    './img/titles2/Medieval.png',

    './js/main.js',
    './js/plugins.js',
    './js/rmmz_core.js',
    './js/rmmz_managers.js',
    './js/rmmz_objects.js',
    './js/rmmz_scenes.js',
    './js/rmmz_sprites.js',
    './js/rmmz_windows.js',

    './js/libs/effekseer.min.js',
    './js/libs/effekseer.wasm',
    './js/libs/localforage.min.js',
    './js/libs/pako.min.js',
    './js/libs/pixi.js',
    './js/libs/vorbisdecoder.js',

    './js/plugins/--------------------------.js',
    './js/plugins/Alpha_NETZ.js',
    './js/plugins/AltMenuScreen.js',
    './js/plugins/AltSaveScreen.js',
    './js/plugins/AutoLifeRing.js',
    './js/plugins/ButtonPicture.js',
    './js/plugins/MathBattleSystem_MZ.js',
    './js/plugins/ProceduralQuestSystem.js',
    './js/plugins/RMMZ_ServiceWorker.js',
    './js/plugins/SimpleEnemyScaling.js',
    './js/plugins/SimpleP2P_Evolution.js',
    './js/plugins/SimpleQuestLog.js',
    './js/plugins/SkillBook.js',
    './js/plugins/TextPicture.js',
    './js/plugins/VisuMZ_0_CoreEngine.js',
    './js/plugins/VisuMZ_1_BattleCore.js',
    './js/plugins/VisuMZ_1_ElementStatusCore.js',
    './js/plugins/VisuMZ_1_EventsMoveCore.js',
    './js/plugins/VisuMZ_1_ItemsEquipsCore.js',
    './js/plugins/VisuMZ_1_MainMenuCore.js',
    './js/plugins/VisuMZ_1_MessageCore.js',
    './js/plugins/VisuMZ_1_OptionsCore.js',
    './js/plugins/VisuMZ_1_SaveCore.js',
    './js/plugins/VisuMZ_1_SkillsStatesCore.js'
];

// Install Event: Download everything right away!
self.addEventListener('install', (event) => {
    self.skipWaiting(); 
    
    event.waitUntil(
        caches.open(CACHE_NAME).then(async (cache) => {
            console.log('Pre-caching all game files. This might take a moment...');
            
            // BEST EFFORT CACHING:
            // It downloads files individually so that if one file breaks or is missing,
            // it keeps downloading the rest without crashing the cache!
            for (let url of PRECACHE_URLS) {
                try {
                    const response = await fetch(url);
                    if (response.ok) {
                        await cache.put(url, response);
                    }
                } catch (e) {
                    console.warn(`Failed to cache ${url} during install. Skipping.`);
                }
            }
            console.log('Offline pre-caching 100% complete!');
        })
    );
});

// Activate Event: Take control and delete older versions
self.addEventListener('activate', (event) => {
    event.waitUntil(self.clients.claim()); 
    event.waitUntil(
        caches.keys().then((cacheNames) => {
            return Promise.all(
                cacheNames.map((cache) => {
                    if (cache !== CACHE_NAME) {
                        console.log('Clearing old cache:', cache);
                        return caches.delete(cache);
                    }
                })
            );
        })
    );
});

// Fetch Event: Serve from cache first, otherwise use network
self.addEventListener('fetch', (event) => {
    if (!event.request.url.startsWith('http')) return;

    event.respondWith(
        caches.match(event.request).then((cachedResponse) => {
            // Serve the file from the hard drive instantly if we have it
            if (cachedResponse) {
                return cachedResponse;
            }

            // Dynamic Fallback: If a new file wasn't in our list above, 
            // download it from the internet and add it to the cache for next time!
            return fetch(event.request).then((networkResponse) => {
                if (!networkResponse || networkResponse.status !== 200 || networkResponse.type !== 'basic') {
                    return networkResponse;
                }
                const responseToCache = networkResponse.clone();
                caches.open(CACHE_NAME).then((cache) => {
                    cache.put(event.request, responseToCache);
                });
                return networkResponse;
            }).catch((err) => {
                console.warn('Asset not cached and user is offline:', event.request.url);
            });
        })
    );
});